// 解压 references/save/template.jkr 并嵌入为 TS 字符串 → src/data/templateSource.ts
// 模板 = 红色牌组、第 1 底注、盲注选择界面开局（PROJECT_SPEC.md 5.2）
// template.jkr 是仓库外活存档 Save/1/save.jkr 的固化副本，勿用活存档覆盖
import { readFileSync, writeFileSync } from 'node:fs';
import { inflateRawSync } from 'node:zlib';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const raw = readFileSync(resolve(ROOT, 'references/save/template.jkr'));
const lua = inflateRawSync(raw).toString('utf8');

if (!lua.startsWith('return ')) throw new Error('模板解压后不是 Lua 表字面量');
const header = `// AUTO-GENERATED by scripts/embedTemplate.mjs — DO NOT EDIT\n// 来源: references/save/template.jkr (raw deflate → UTF-8 Lua 源码, ${raw.length} 字节压缩 / ${lua.length} 字符解压)\n`;
const body = `export const templateSource: string = ${JSON.stringify(lua)};\nexport default templateSource;\n`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/templateSource.ts'), header + body);
console.log(`embedded template: ${raw.length} compressed bytes -> ${lua.length} chars of Lua source`);
