// 从 Code/game.lua 与 Code/localization/zh_CN.lua 提取牌组定义 → src/data/backs.ts
// 单向生成：改数据必须改本脚本后重跑（PROJECT_SPEC.md 2.3/7）
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const gameLua = readFileSync(resolve(ROOT, 'Code/game.lua'), 'utf8');
const zhLua = readFileSync(resolve(ROOT, 'Code/localization/zh_CN.lua'), 'utf8');

/** 从 src[start]（必须为 '{'）平衡扫描到匹配的 '}'，返回含两侧括号的子串 */
function balancedFrom(src, start) {
  if (src[start] !== '{') throw new Error(`balancedFrom: src[start] 不是 '{'`);
  let depth = 0, i = start;
  while (i < src.length) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') { depth--; if (depth === 0) break; }
    i++;
  }
  return src.slice(start, i + 1);
}

/** 平衡花括号截取 `key={` 的完整块 */
function extractBlock(src, key) {
  const m = new RegExp(`${key}\\s*=\\s*\\{`).exec(src);
  if (!m) return null;
  return balancedFrom(src, m.index + m[0].length - 1);
}

/** 解析单行 Lua 表字面量（b_* 定义都是单行、仅含字符串/数字/布尔/嵌套表） */
function parseLuaLiteral(src) {
  let pos = 0;
  function skipWs() { while (pos < src.length && /\s/.test(src[pos])) pos++; }
  function parseTable() {
    pos++; // {
    const out = {};
    let arrIdx = 0;
    for (;;) {
      skipWs();
      if (src[pos] === '}') { pos++; return out; }
      // 尝试 key=value；否则按位置元素（数组式表，如 consumables = {'c_fool', 'c_fool'}）
      const km = /^([A-Za-z_]\w*)\s*=/.exec(src.slice(pos));
      if (km) {
        pos += km[0].length;
        skipWs();
        out[km[1]] = parseValue();
      } else {
        arrIdx++;
        out[arrIdx] = parseValue();
      }
      skipWs();
      if (src[pos] === ',') pos++;
    }
  }
  function parseValue() {
    skipWs();
    if (src[pos] === '{') return parseTable();
    if (src[pos] === '"' || src[pos] === "'") {
      const q = src[pos];
      const m = new RegExp(`^${q}((?:[^${q}\\\\]|\\\\.)*)${q}`).exec(src.slice(pos));
      pos += m[0].length;
      return m[1];
    }
    const m = /^(true|false|-?\d+\.?\d*(?:e[-+]?\d+)?)/.exec(src.slice(pos));
    if (!m) throw new Error(`bad value at ${pos}: ${src.slice(pos, pos + 30)}`);
    pos += m[0].length;
    return m[1] === 'true' ? true : m[1] === 'false' ? false : Number(m[1]);
  }
  return parseTable();
}

// ---- 1. game.lua 的 b_* 定义 ----
const backDefs = [];
for (const line of gameLua.split('\n')) {
  const m = /^\s{8}(b_\w+)\s*=\s*\{.+\},?\s*$/.exec(line);
  if (m) backDefs.push([m[1], parseLuaLiteral(line.slice(line.indexOf('{')))]);
}

// ---- 2. zh_CN 的名称与描述 ----
const zhNames = {};
function zhName(key) {
  const block = extractBlock(zhLua, key);
  if (!block) return undefined;
  const m = /name\s*=\s*"((?:[^"\\]|\\.)*)"/.exec(block);
  return m ? m[1] : undefined;
}
function zhText(key) {
  const block = extractBlock(zhLua, key);
  if (!block) return [];
  const tm = /text\s*=\s*\{/.exec(block);
  if (!tm) return [];
  const arrSrc = balancedFrom(block, tm.index + tm[0].length - 1);
  return [...arrSrc.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map(x => x[1]);
}
for (const [key] of backDefs) zhNames[key] = { name: zhName(key), text: zhText(key) };

// ---- 3. 描述占位符 #N# 的替换值 ----
// 依据 game.lua 的 b_* config 与 back.lua/card.lua 的 apply_to_run 规则（PROJECT_SPEC.md 5.4）
const ZH = {
  v_crystal_ball: zhName('v_crystal_ball'), v_telescope: zhName('v_telescope'),
  v_tarot_merchant: zhName('v_tarot_merchant'), v_planet_merchant: zhName('v_planet_merchant'),
  v_overstock_norm: zhName('v_overstock_norm'), c_fool: zhName('c_fool'),
  tag_double: zhName('tag_double'),
};
const VARS = {
  b_red: [1], b_blue: [1], b_yellow: [10],
  b_green: [2, 1], b_black: [1, 1],
  b_magic: [ZH.v_crystal_ball, ZH.c_fool],
  b_nebula: [ZH.v_telescope, -1],
  b_zodiac: [ZH.v_tarot_merchant, ZH.v_planet_merchant, ZH.v_overstock_norm],
  b_painted: [2, -1], b_anaglyph: [ZH.tag_double], b_plasma: [2],
};

// ---- 4. 输出 backs.ts ----
const backs = backDefs.map(([key, def]) => ({
  key,
  enName: def.name,
  zhName: zhNames[key].name ?? def.name,
  order: def.order,
  pos: def.pos,
  stake: def.stake,
  omit: def.omit === true,
  config: def.config ?? {},
  text: zhNames[key].text ?? [],
  vars: VARS[key] ?? [],
})).sort((a, b) => a.order - b.order);

const header = `// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT\n// 来源: Code/game.lua P_CENTERS + Code/localization/zh_CN.lua\n`;
const body = `export interface BackDef {\n  key: string;\n  enName: string;\n  zhName: string;\n  order: number;\n  pos: { x: number; y: number };\n  stake: number;\n  omit: boolean;\n  config: Record<string, unknown>;\n  text: string[];\n  vars: (number | string)[];\n}\n\nexport const BACKS: BackDef[] = ${JSON.stringify(backs, null, 2)};\n`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/backs.ts'), header + body);

const selectable = backs.filter(b => !b.omit);
console.log(`extracted ${backs.length} backs (${selectable.length} selectable):`);
for (const b of backs) console.log(`  ${b.key} #${b.order} ${b.zhName} (${b.enName})${b.omit ? ' [omit]' : ''}`);

// ---- 5. 提取赌注（Stake）定义 → src/data/stakes.ts ----
// game.lua P_CENTER_POOLS.Stake 的 stake_level 顺序：白1 红2 绿3 黑4 蓝5 紫6 橙7 金8
const STAKE_KEYS = ['stake_white', 'stake_red', 'stake_green', 'stake_black',
  'stake_blue', 'stake_purple', 'stake_orange', 'stake_gold'];
const CHIP_FILES = ['White Chip.png', 'Red Chip.png', 'Green Chip.png', 'Black Chip.png',
  'Blue Chip.png', 'Purple Chip.png', 'Orange Chip.png', 'Gold Chip.png'];
const stakes = STAKE_KEYS.map((key, i) => ({
  level: i + 1,
  key,
  zhName: zhName(key) ?? key,
  chipFile: CHIP_FILES[i],
  text: zhText(key),
}));
const stakeHeader = `// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT\n// 来源: game.lua P_CENTER_POOLS.Stake + Code/localization/zh_CN.lua\n`;
const stakeBody = `export interface StakeDef {\n  level: number;\n  key: string;\n  zhName: string;\n  chipFile: string;\n  text: string[];\n}\n\nexport const STAKES: StakeDef[] = ${JSON.stringify(stakes, null, 2)};\n`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/stakes.ts'), stakeHeader + stakeBody);
console.log(`extracted ${stakes.length} stakes:`);
for (const s of stakes) console.log(`  #${s.level} ${s.zhName} (${s.key})`);
