// 从 Code/game.lua 与 Code/localization/zh_CN.lua 提取牌组定义 → src/data/backs.ts
// 单向生成：改数据必须改本脚本后重跑（PROJECT_SPEC.md 2.3/7）
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const gameLua = readFileSync(resolve(ROOT, 'Code/game.lua'), 'utf8');
const zhLua = readFileSync(resolve(ROOT, 'Code/localization/zh_CN.lua'), 'utf8');

/** 从 src[start]（必须为 '{'）平衡扫描到匹配的 '}'，返回含两侧括号的子串 */
function balancedFrom(src, start) {
  if (src[start] !== '{') throw new Error(`balancedFrom: src[start] 不是 '{'`);
  let depth = 0, i = start;
  while (i < src.length) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') { depth--; if (depth === 0) break; }
    i++;
  }
  return src.slice(start, i + 1);
}

/** 平衡花括号截取 `key={` 的完整块 */
function extractBlock(src, key) {
  const m = new RegExp(`${key}\\s*=\\s*\\{`).exec(src);
  if (!m) return null;
  return balancedFrom(src, m.index + m[0].length - 1);
}

/** 解析单行 Lua 表字面量（b_* 定义都是单行、仅含字符串/数字/布尔/嵌套表） */
function parseLuaLiteral(src) {
  let pos = 0;
  function skipWs() { while (pos < src.length && /\s/.test(src[pos])) pos++; }
  function parseTable() {
    pos++; // {
    const out = {};
    let arrIdx = 0;
    for (;;) {
      skipWs();
      if (src[pos] === '}') { pos++; return out; }
      // 尝试 key=value；否则按位置元素（数组式表，如 consumables = {'c_fool', 'c_fool'}）
      const km = /^([A-Za-z_]\w*)\s*=/.exec(src.slice(pos));
      if (km) {
        pos += km[0].length;
        skipWs();
        out[km[1]] = parseValue();
      } else {
        arrIdx++;
        out[arrIdx] = parseValue();
      }
      skipWs();
      if (src[pos] === ',') pos++;
    }
  }
  function parseValue() {
    skipWs();
    if (src[pos] === '{') return parseTable();
    if (src[pos] === '"' || src[pos] === "'") {
      const q = src[pos];
      const m = new RegExp(`^${q}((?:[^${q}\\\\]|\\\\.)*)${q}`).exec(src.slice(pos));
      pos += m[0].length;
      return m[1];
    }
    const m = /^(true|false|-?\d+\.?\d*(?:e[-+]?\d+)?)/.exec(src.slice(pos));
    if (!m) throw new Error(`bad value at ${pos}: ${src.slice(pos, pos + 30)}`);
    pos += m[0].length;
    return m[1] === 'true' ? true : m[1] === 'false' ? false : Number(m[1]);
  }
  return parseTable();
}

// ---- 1. game.lua 的 b_* 定义 ----
const backDefs = [];
for (const line of gameLua.split('\n')) {
  const m = /^\s{8}(b_\w+)\s*=\s*\{.+\},?\s*$/.exec(line);
  if (m) backDefs.push([m[1], parseLuaLiteral(line.slice(line.indexOf('{')))]);
}

// ---- 2. zh_CN 的名称与描述 ----
const zhNames = {};
/** 取 zh_CN 中 key 块的 name 字段；src 可指定为某个已截取的子块（避免同名键互相干扰） */
function zhName(key, src = zhLua) {
  const block = extractBlock(src, key);
  if (!block) return undefined;
  const m = /name\s*=\s*"((?:[^"\\]|\\.)*)"/.exec(block);
  return m ? m[1] : undefined;
}
function zhText(key, src = zhLua) {
  const block = extractBlock(src, key);
  if (!block) return [];
  const tm = /text\s*=\s*\{/.exec(block);
  if (!tm) return [];
  const arrSrc = balancedFrom(block, tm.index + tm[0].length - 1);
  return [...arrSrc.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map(x => x[1]);
}
for (const [key] of backDefs) zhNames[key] = { name: zhName(key), text: zhText(key) };

// ---- 3. 描述占位符 #N# 的替换值 ----
// 依据 game.lua 的 b_* config 与 back.lua/card.lua 的 apply_to_run 规则（PROJECT_SPEC.md 5.4）
const ZH = {
  v_crystal_ball: zhName('v_crystal_ball'), v_telescope: zhName('v_telescope'),
  v_tarot_merchant: zhName('v_tarot_merchant'), v_planet_merchant: zhName('v_planet_merchant'),
  v_overstock_norm: zhName('v_overstock_norm'), c_fool: zhName('c_fool'),
  tag_double: zhName('tag_double'),
};
const VARS = {
  b_red: [1], b_blue: [1], b_yellow: [10],
  b_green: [2, 1], b_black: [1, 1],
  b_magic: [ZH.v_crystal_ball, ZH.c_fool],
  b_nebula: [ZH.v_telescope, -1],
  b_zodiac: [ZH.v_tarot_merchant, ZH.v_planet_merchant, ZH.v_overstock_norm],
  b_painted: [2, -1], b_anaglyph: [ZH.tag_double], b_plasma: [2],
};

// ---- 4. 输出 backs.ts ----
const backs = backDefs.map(([key, def]) => ({
  key,
  enName: def.name,
  zhName: zhNames[key].name ?? def.name,
  order: def.order,
  pos: def.pos,
  stake: def.stake,
  omit: def.omit === true,
  config: def.config ?? {},
  text: zhNames[key].text ?? [],
  vars: VARS[key] ?? [],
})).sort((a, b) => a.order - b.order);

const header = `// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT\n// 来源: Code/game.lua P_CENTERS + Code/localization/zh_CN.lua\n`;
const body = `export interface BackDef {\n  key: string;\n  enName: string;\n  zhName: string;\n  order: number;\n  pos: { x: number; y: number };\n  stake: number;\n  omit: boolean;\n  config: Record<string, unknown>;\n  text: string[];\n  vars: (number | string)[];\n}\n\nexport const BACKS: BackDef[] = ${JSON.stringify(backs, null, 2)};\n`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/backs.ts'), header + body);

const selectable = backs.filter(b => !b.omit);
console.log(`extracted ${backs.length} backs (${selectable.length} selectable):`);
for (const b of backs) console.log(`  ${b.key} #${b.order} ${b.zhName} (${b.enName})${b.omit ? ' [omit]' : ''}`);

// ---- 5. 提取赌注（Stake）定义 → src/data/stakes.ts ----
// game.lua P_CENTER_POOLS.Stake 的 stake_level 顺序：白1 红2 绿3 黑4 蓝5 紫6 橙7 金8
const STAKE_KEYS = ['stake_white', 'stake_red', 'stake_green', 'stake_black',
  'stake_blue', 'stake_purple', 'stake_orange', 'stake_gold'];
const CHIP_FILES = ['White Chip.png', 'Red Chip.png', 'Green Chip.png', 'Black Chip.png',
  'Blue Chip.png', 'Purple Chip.png', 'Orange Chip.png', 'Gold Chip.png'];
const stakes = STAKE_KEYS.map((key, i) => ({
  level: i + 1,
  key,
  zhName: zhName(key) ?? key,
  chipFile: CHIP_FILES[i],
  text: zhText(key),
}));
const stakeHeader = `// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT\n// 来源: game.lua P_CENTER_POOLS.Stake + Code/localization/zh_CN.lua\n`;
const stakeBody = `export interface StakeDef {\n  level: number;\n  key: string;\n  zhName: string;\n  chipFile: string;\n  text: string[];\n}\n\nexport const STAKES: StakeDef[] = ${JSON.stringify(stakes, null, 2)};\n`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/stakes.ts'), stakeHeader + stakeBody);
console.log(`extracted ${stakes.length} stakes:`);
for (const s of stakes) console.log(`  #${s.level} ${s.zhName} (${s.key})`);

// ---- 6. 提取增强（P_CENTERS m_*）与蜡封（P_SEALS）→ src/data/cardMods.ts ----
// 增强：卡面底图文件名 = center.label（如 "Glass Card"），存档写 save_fields.center = key、ability 由 config 重算
const enhancedZh = extractBlock(zhLua, 'Enhanced') ?? '';
const enhancements = gameLua.split('\n')
  .map(line => /^\s{8}(m_\w+)\s*=\s*\{.+\},?\s*$/.exec(line))
  .filter(Boolean)
  .map(m => [m[1], parseLuaLiteral(m[0].slice(m[0].indexOf('{')))])
  .map(([key, def]) => ({
    key,
    enName: def.name,
    zhName: zhName(key, enhancedZh) ?? def.name,
    /** 卡面底图文件名（assets/enhancement/<image>，= 游戏资源名 Resources/enhancement/<name>.png） */
    image: `${def.name}.png`,
    /** 存档 card.label（= center.label，如 m_bonus 是 "Bonus Card"） */
    label: def.label ?? def.name,
    order: def.order,
    config: def.config ?? {},
  })).sort((a, b) => a.order - b.order);

// 蜡封：存档写字符串 key（Red/Blue/Gold/Purple）；蜡封图 Resources/seal/<key>.png
const sealsBlock = extractBlock(gameLua, 'self.P_SEALS') ?? '';
const otherZh = extractBlock(zhLua, 'Other') ?? '';
const seals = [...sealsBlock.matchAll(/(\w+)\s*=\s*\{\s*order\s*=\s*(\d+)/g)]
  .map(([, key, order]) => ({
    key,
    zhName: zhName(`${key.toLowerCase()}_seal`, otherZh) ?? key,
    image: `${key}.png`,
    order: Number(order),
  })).sort((a, b) => a.order - b.order);

// ---- 6b. 提取版本（P_CENTERS e_*）→ EDITIONS（与增强/蜡封同文件）
// key 去掉 e_ 前缀 = shader 名（resources/shaders/<key>.fs）= 存档 card.edition 字段名
// e_base（无效果）不收录；config.extra 是效果数值（闪箔 +50 筹码 / 镭射 +10 倍率 / 多彩 X1.5 / 负片 +1 槽）
const editions = gameLua.split('\n')
  .map(line => /^\s{8}(e_\w+)\s*=\s*\{.+\},?\s*$/.exec(line))
  .filter(Boolean)
  .map(m => [m[1], parseLuaLiteral(m[0].slice(m[0].indexOf('{')))])
  .filter(([key]) => key !== 'e_base')
  .map(([key, def]) => ({
    key: key.slice(2),
    enName: def.name,
    zhName: zhName(key) ?? def.name,
    order: def.order,
    config: def.config ?? {},
  })).sort((a, b) => a.order - b.order);

// ---- 6c. 提取配色：globals.lua 的 G.C 色值 + UI_definitions.lua 的 G.BADGE_COL ----
// 用途：扑克详情里「增强 / 蜡封 / 版本」的值按游戏配色上色。
// 依据游戏的 create_badge（UI_definitions.lua:1153）：底色 = 物品色、文字纯白。
//   蜡封 → G.BADGE_COL 的 *_seal（金 GOLD / 红 RED / 蓝 BLUE / 紫 PURPLE）
//   版本 → 四种在游戏里统一是 G.C.DARK_EDITION（黑）
//   增强 → G.C.SECONDARY_SET.Enhanced（分类色，所有增强共用）
const globalsLua = readFileSync(resolve(ROOT, 'Code/globals.lua'), 'utf8');
const uiDefsLua = readFileSync(resolve(ROOT, 'Code/functions/UI_definitions.lua'), 'utf8');

/** 取 needle 之后第一个 '{' 起的完整平衡块 */
const blockAfter = (src, needle) => {
  const i = src.indexOf(needle);
  return i < 0 ? '' : balancedFrom(src, src.indexOf('{', i));
};

const colourOf = {};
// HEX("009dff") / HEX('FE5F55')；8 位含 alpha（如 8389DDFF）取前 6 位
for (const m of globalsLua.matchAll(/([A-Z][A-Z_0-9]*)\s*=\s*HEX\(\s*["']([0-9a-fA-F]{6,8})["']\s*\)/g)) {
  colourOf[m[1]] = `#${m[2].slice(0, 6).toLowerCase()}`;
}
// 四元色（如 DARK_EDITION = {0,0,0,1}）→ #rrggbb
for (const m of globalsLua.matchAll(/([A-Z][A-Z_0-9]*)\s*=\s*\{\s*([01](?:\.\d+)?)\s*,\s*([01](?:\.\d+)?)\s*,\s*([01](?:\.\d+)?)\s*,\s*([01](?:\.\d+)?)\s*\}/g)) {
  const h = (v) => Math.round(Number(v) * 255).toString(16).padStart(2, '0');
  colourOf[m[1]] = `#${h(m[2])}${h(m[3])}${h(m[4])}`;
}

const badgeColour = {};
for (const m of blockAfter(uiDefsLua, 'G.BADGE_COL').matchAll(/(\w+)\s*=\s*G\.C\.(\w+)/g)) {
  if (colourOf[m[2]]) badgeColour[m[1]] = colourOf[m[2]];
}
const enhancedColour = /Enhanced\s*=\s*HEX\(\s*["']([0-9a-fA-F]{6,8})["']\s*\)/
  .exec(blockAfter(globalsLua, 'SECONDARY_SET'))?.[1];
const enhancedHex = enhancedColour ? `#${enhancedColour.slice(0, 6).toLowerCase()}` : undefined;

// 挂到三类数据上（形状统一：def.colour）
for (const s of seals) s.colour = badgeColour[`${s.key.toLowerCase()}_seal`];
for (const e of editions) e.colour = badgeColour[e.key === 'holo' ? 'holographic' : e.key];
for (const e of enhancements) e.colour = enhancedHex;

// 版本徽章的底色在游戏里是**逐帧呼吸**的：主循环每帧改写 G.C.DARK_EDITION
// （game.lua:2500-2502）——R = base+amp*sin(w*t)、B = base+amp*(1-sin(w*t))、G = min(R,B)。
// 故徽章（UI_definitions.lua:1140-1143 四种版本都取 DARK_EDITION）底色在两色之间往返。
const pulse = /C\.DARK_EDITION\[1\]\s*=\s*([\d.]+)\s*\+\s*([\d.]+)\s*\*\s*math\.sin\(\s*self\.TIMERS\.REAL\s*\*\s*([\d.]+)\s*\)/.exec(gameLua);
let editionPulse;
if (pulse) {
  const base = Number(pulse[1]), amp = Number(pulse[2]), w = Number(pulse[3]);
  const hex = (r, g, b) => `#${[r, g, b].map(v => Math.round(Math.max(0, Math.min(1, v)) * 255).toString(16).padStart(2, '0')).join('')}`;
  // 直接按公式求值（避免手推相位出错）：R = base+amp*s，B = base+amp*(1-s)，G = min(R,B)
  const at = (s) => {
    const r = base + amp * s;
    const b = base + amp * (1 - s);
    return hex(r, Math.min(r, b), b);
  };
  const warm = at(1);      // sin=+1：R 最大、B 最小
  const mid = at(0);       // sin=0：中位
  const cool = at(-1);     // sin=-1：R 最小、B 最大
  editionPulse = { warm, mid, cool, period: Number((2 * Math.PI / w).toFixed(3)) };
  for (const e of editions) e.colour = mid;       // 静止/降低动态时的回退色取中位
  console.log(`edition badge pulse ${editionPulse.period}s: ${warm} → ${mid} → ${cool}`);
} else {
  console.warn('未找到 G.C.DARK_EDITION 的呼吸公式（game.lua），版本徽章将使用静态色');
}

const pulseTs = editionPulse ?? { warm: badgeColour.foil ?? '#000000', mid: badgeColour.foil ?? '#000000', cool: badgeColour.foil ?? '#000000', period: 4.833 };

const modsBody = `export interface EnhancementDef {\n  key: string;\n  enName: string;\n  zhName: string;\n  /** 卡面底图文件名：assets/enhancement/<image> */\n  image: string;\n  /** 存档 card.label（= center.label） */\n  label: string;\n  order: number;\n  config: Record<string, number>;\n  /** 标签底色（G.C.SECONDARY_SET.Enhanced，所有增强共用；游戏不改写此色，静态） */\n  colour: string;\n}\n\nexport interface SealDef {\n  key: string;\n  zhName: string;\n  /** assets/seal/<image> */\n  image: string;\n  order: number;\n  /** 标签底色（G.BADGE_COL.<key>_seal：金 GOLD / 红 RED / 蓝 BLUE / 紫 PURPLE；游戏不改写，静态） */\n  colour: string;\n}\n\nexport interface EditionDef {\n  /** foil / holo / polychrome / negative：= shader 名（resources/shaders/<key>.fs）= 存档 card.edition 字段名 */\n  key: string;\n  enName: string;\n  zhName: string;\n  order: number;\n  /** 中心 config，extra 为效果数值（由 core/saveDeck 按 set_edition 规则映射到 chips/mult/x_mult） */\n  config: Record<string, number>;\n  /** 标签底色的中位色（DARK_EDITION 呼吸的中点；降低动态/无法动画时使用） */\n  colour: string;\n}\n\n/** 版本徽章底色的呼吸：游戏主循环每帧改写 G.C.DARK_EDITION（game.lua:2500-2502），\n *  R = base+amp*sin(w*t)、B = base+amp*(1-sin)、G = min(R,B)，周期 2π/w。四种版本共用同一色（同呼吸）。 */\nexport const EDITION_PULSE: { warm: string; mid: string; cool: string; period: number } = ${JSON.stringify(pulseTs)};\n\nexport const ENHANCEMENTS: EnhancementDef[] = ${JSON.stringify(enhancements, null, 2)};\n\nexport const SEALS: SealDef[] = ${JSON.stringify(seals, null, 2)};\n\nexport const EDITIONS: EditionDef[] = ${JSON.stringify(editions, null, 2)};\n`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/cardMods.ts'),
  `// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT\n// 来源: game.lua P_CENTERS(m_* / e_*) / P_SEALS + globals.lua G.C + UI_definitions.lua G.BADGE_COL + Code/localization/zh_CN.lua\n` + modsBody);
console.log(`extracted ${enhancements.length} enhancements:`);
for (const e of enhancements) console.log(`  ${e.key} #${e.order} ${e.zhName} (${e.enName}) colour=${e.colour}`);
console.log(`extracted ${seals.length} seals:`);
for (const s of seals) console.log(`  ${s.key} #${s.order} ${s.zhName} colour=${s.colour}`);
console.log(`extracted ${editions.length} editions:`);
for (const e of editions) console.log(`  ${e.key} #${e.order} ${e.zhName} (${e.enName}) extra=${e.config.extra} colour=${e.colour}`);

// ---- 7. 提取消耗牌（P_CENTERS 的 c_* → Tarot / Planet / Spectral）→ src/data/consumables.ts ----
// 牌池顺序 = 游戏 P_CENTER_POOLS 的排法（按 order 升序，game.lua:827-830），故按 order 排序即可；
// 只收 consumeable = true 且 set 属于三类的中心，c_locked / t_undiscovered 等占位中心自动排除。
const CONSUMABLE_SETS = ['Tarot', 'Planet', 'Spectral'];
const consumables = gameLua.split('\n')
  .map(line => /^\s{8}(c_\w+)\s*=\s*\{.+\},?\s*$/.exec(line))
  .filter(Boolean)
  .map(m => [m[1], parseLuaLiteral(m[0].slice(m[0].indexOf('{')))])
  .filter(([, def]) => def.consumeable === true && CONSUMABLE_SETS.includes(def.set))
  .map(([key, def]) => ({ key, def }));

// 牌型 → 1 级基础数值（Planet 描述里的 #3#/#4#；game.lua:2001 hands 表）
const handBase = {};
for (const line of gameLua.split('\n')) {
  const m = /^\s*\["([^"]+)"\]\s*=\s*\{[^}]*?l_mult\s*=\s*([\d.]+)[^}]*?l_chips\s*=\s*([\d.]+)/.exec(line);
  if (m) handBase[m[1]] = { l_mult: Number(m[2]), l_chips: Number(m[3]) };
}
// 牌型 / 花色中文名（zh_CN 的 poker_hands 与 suits_plural）
// 注意键有两种写法：["Flush House"] 与 Pair=（无引号、无方括号）；后者必须以 \w 起头，
// 否则惰性量词会从行首空格开始匹配，得到带前导空格的键名
const handZh = {};
for (const m of (extractBlock(zhLua, 'poker_hands') ?? '').matchAll(/\[?"?(\w[\w ]*?)"?\]?\s*=\s*"([^"]+)"/g)) handZh[m[1].trim()] = m[2];
const suitZh = {};
for (const m of (extractBlock(zhLua, 'suits_plural') ?? '').matchAll(/(\w+)\s*=\s*"([^"]+)"/g)) suitZh[m[1]] = m[2];
const enhZh = new Map(enhancements.map(e => [e.key, e.zhName]));
// 分类色（globals.lua SECONDARY_SET：塔罗紫 / 星球青 / 幻灵蓝）
const secondarySet = {};
for (const m of (blockAfter(globalsLua, 'SECONDARY_SET')).matchAll(/(\w+)\s*=\s*HEX\(\s*["']([0-9a-fA-F]{6,8})["']\)/g)) {
  secondarySet[m[1]] = `#${m[2].slice(0, 6).toLowerCase()}`;
}

/** 按游戏 generate_card_ui 的 loc_vars 规则给出 #N# 候选取值（common_events.lua:2623-2712）。
 *  全部取「开局状态」：等级 1、无小丑、概率基数 1（G.GAME.probabilities.normal）。 */
function consumableVarValues(key, def) {
  const c = def.config ?? {};
  if (def.set === 'Planet') {
    const base = handBase[c.hand_type] ?? { l_mult: 0, l_chips: 0 };
    return [1, handZh[c.hand_type] ?? c.hand_type, base.l_mult, base.l_chips];
  }
  if (def.set === 'Spectral') {
    // 使魔/严峻/咒语取 extra；火祭取 {destroy, dollars}；神秘生物取 extra；灵质的 #1# = ecto_minus（开局 1）
    if (key === 'c_immolate') return [c.extra?.destroy, c.extra?.dollars];
    if (key === 'c_ectoplasm') return [1];
    if (c.extra !== undefined && typeof c.extra === 'number') return [c.extra];
    return [];
  }
  // Tarot：#1# 多为 max_highlighted，#2# 是增强/花色名（命运之轮与节制例外）
  switch (key) {
    case 'c_wheel_of_fortune': return [1, c.extra];
    case 'c_temperance': return [c.extra, 0];   // #2# = min(extra, 小丑售价和)：开局无小丑 → 0
    case 'c_star': case 'c_moon': case 'c_sun': case 'c_world':
      return [c.max_highlighted, suitZh[c.suit_conv] ?? c.suit_conv];
    case 'c_magician': case 'c_empress': case 'c_heirophant': case 'c_lovers':
    case 'c_chariot': case 'c_justice': case 'c_devil': case 'c_tower':
      return [c.max_highlighted, enhZh.get(c.mod_conv) ?? c.mod_conv];
    default: break;
  }
  if (c.mod_conv === 'up_rank') return [c.max_highlighted, '点数'];   // 力量：#2# 未被文本使用
  if (c.planets !== undefined) return [c.planets];
  if (c.tarots !== undefined) return [c.tarots];
  if (c.extra !== undefined) return [c.extra];
  if (c.max_highlighted !== undefined) return [c.max_highlighted];
  return [];
}

const consumableDefs = CONSUMABLE_SETS.flatMap(set => {
  const zhBlock = extractBlock(zhLua, set) ?? '';
  return consumables.filter(c => c.def.set === set).map(({ key, def }) => {
    const text = zhText(key, zhBlock);
    // 取值表按文本真正用到的最大序号截断：文本没用到的位置不上屏（如力量只用 #1#）
    const used = Math.max(0, ...[...text.join('').matchAll(/#(\d+)#/g)].map(m => Number(m[1])), 0);
    const vars = consumableVarValues(key, def).slice(0, used);
    if (vars.length < used) console.warn(`  ! ${key} 的 #N# 取值不足（用 ${used} 个，得 ${vars.length} 个），对应描述行将不显示`);
    return {
      key,
      enName: def.name,
      zhName: zhName(key, zhBlock) ?? def.name,
      set: def.set,
      order: def.order,
      cost: def.cost,
      pos: def.pos,
      /** 素材文件名（含空格，1:1 复制自 Resources/<set>/） */
      image: `${def.name}.png`,
      hidden: def.hidden === true,
      effect: def.effect,
      config: def.config ?? {},
      text,
      vars,
      colour: secondarySet[def.set] ?? '#ffffff',
    };
  }).sort((a, b) => a.order - b.order);
});

const consumableBody = `export type ConsumableSet = 'Tarot' | 'Planet' | 'Spectral';

export interface ConsumableDef {
  key: string;
  /** 英文名 = 素材文件名前缀（assets/{tarot|planet|spectral}/<enName>.png） */
  enName: string;
  zhName: string;
  set: ConsumableSet;
  order: number;
  /** 售价（塔罗/星球 3、幻灵 4）；开局持有实例的 sell_cost = floor(cost / 2) */
  cost: number;
  /** Tarots.png 图集坐标（10 列 × 6 行，格 142×190） */
  pos: { x: number; y: number };
  /** 素材文件名（保留原始空格） */
  image: string;
  /** 未解锁（灵魂 / 黑洞）：游戏内以占位图隐藏 */
  hidden: boolean;
  effect?: string;
  /** 中心 config，消耗牌效果参数的存档来源 */
  config: Record<string, unknown>;
  /** 中文描述行（原始文本，含 {C:xx} 标记与 #N# 占位符） */
  text: string[];
  /** #N# 取值（开局状态静态解析；序号未用到的位置不占位） */
  vars: (number | string)[];
  /** 分类色（G.C.SECONDARY_SET：塔罗紫 / 星球青 / 幻灵蓝） */
  colour: string;
}

export const CONSUMABLES: ConsumableDef[] = ${JSON.stringify(consumableDefs, null, 2)};
`;
writeFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/consumables.ts'),
  `// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT\n// 来源: Code/game.lua P_CENTERS(c_*) / P_CENTER_POOLS + Code/localization/zh_CN.lua + globals.lua G.C.SECONDARY_SET\n` + consumableBody);
for (const set of CONSUMABLE_SETS) {
  const list = consumableDefs.filter(d => d.set === set);
  console.log(`extracted ${list.length} ${set} consumables:`);
  for (const d of list) console.log(`  ${d.key} #${d.order} ${d.zhName} (${d.enName}) cost=${d.cost} pos=${d.pos.x},${d.pos.y} vars=[${d.vars.join(',')}]${d.hidden ? ' [hidden]' : ''}`);
}
