// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: Code/game.lua P_CENTERS + Code/localization/zh_CN.lua
export interface BackDef {
  key: string;
  enName: string;
  zhName: string;
  order: number;
  pos: { x: number; y: number };
  stake: number;
  omit: boolean;
  config: Record<string, unknown>;
  text: string[];
  vars: (number | string)[];
}

export const BACKS: BackDef[] = [
  {
    "key": "b_red",
    "enName": "Red Deck",
    "zhName": "红色牌组",
    "order": 1,
    "pos": {
      "x": 0,
      "y": 0
    },
    "stake": 1,
    "omit": false,
    "config": {
      "discards": 1
    },
    "text": [
      "每回合",
      "{C:red}+#1#{}次弃牌"
    ],
    "vars": [
      1
    ]
  },
  {
    "key": "b_blue",
    "enName": "Blue Deck",
    "zhName": "蓝色牌组",
    "order": 2,
    "pos": {
      "x": 0,
      "y": 2
    },
    "stake": 1,
    "omit": false,
    "config": {
      "hands": 1
    },
    "text": [
      "每回合",
      "{C:blue}+#1#{}次出牌"
    ],
    "vars": [
      1
    ]
  },
  {
    "key": "b_yellow",
    "enName": "Yellow Deck",
    "zhName": "黄色牌组",
    "order": 3,
    "pos": {
      "x": 1,
      "y": 2
    },
    "stake": 1,
    "omit": false,
    "config": {
      "dollars": 10
    },
    "text": [
      "开局时",
      "额外获得{C:money}$#1#"
    ],
    "vars": [
      10
    ]
  },
  {
    "key": "b_green",
    "enName": "Green Deck",
    "zhName": "绿色牌组",
    "order": 4,
    "pos": {
      "x": 2,
      "y": 2
    },
    "stake": 1,
    "omit": false,
    "config": {
      "extra_hand_bonus": 2,
      "extra_discard_bonus": 1,
      "no_interest": true
    },
    "text": [
      "每回合结束时：",
      "每剩一次{C:blue}出牌次数，获得{C:money}$#1#{s:0.85}",
      "每剩一次{C:red}弃牌次数，获得{C:money}$#2#{s:0.85}",
      "不赚取任何{C:attention}利息"
    ],
    "vars": [
      2,
      1
    ]
  },
  {
    "key": "b_black",
    "enName": "Black Deck",
    "zhName": "黑色牌组",
    "order": 5,
    "pos": {
      "x": 3,
      "y": 2
    },
    "stake": 1,
    "omit": false,
    "config": {
      "hands": -1,
      "joker_slot": 1
    },
    "text": [
      "小丑牌槽位{C:attention}+#1#{}",
      "",
      "每回合",
      "出牌次数{C:blue}-#2#{}"
    ],
    "vars": [
      1,
      1
    ]
  },
  {
    "key": "b_magic",
    "enName": "Magic Deck",
    "zhName": "魔法牌组",
    "order": 6,
    "pos": {
      "x": 0,
      "y": 3
    },
    "stake": 1,
    "omit": false,
    "config": {
      "voucher": "v_crystal_ball",
      "consumables": {
        "1": "c_fool",
        "2": "c_fool"
      }
    },
    "text": [
      "开局时拥有",
      "{C:tarot,T:v_crystal_ball}#1#{}优惠券",
      "和{C:attention}2{}张{C:tarot,T:c_fool}#2#"
    ],
    "vars": [
      "水晶球",
      "愚者"
    ]
  },
  {
    "key": "b_nebula",
    "enName": "Nebula Deck",
    "zhName": "星云牌组",
    "order": 7,
    "pos": {
      "x": 3,
      "y": 0
    },
    "stake": 1,
    "omit": false,
    "config": {
      "voucher": "v_telescope",
      "consumable_slot": -1
    },
    "text": [
      "开局时拥有",
      "{C:planet,T:v_telescope}#1#{}优惠券",
      "消耗牌槽位{C:red}#2#{}"
    ],
    "vars": [
      "望远镜",
      -1
    ]
  },
  {
    "key": "b_ghost",
    "enName": "Ghost Deck",
    "zhName": "幽灵牌组",
    "order": 8,
    "pos": {
      "x": 6,
      "y": 2
    },
    "stake": 1,
    "omit": false,
    "config": {
      "spectral_rate": 2,
      "consumables": {
        "1": "c_hex"
      }
    },
    "text": [
      "商店中可能",
      "出现{C:spectral}幻灵牌{}",
      "初始带有{C:spectral,T:c_hex}妖法{}牌"
    ],
    "vars": []
  },
  {
    "key": "b_abandoned",
    "enName": "Abandoned Deck",
    "zhName": "废弃牌组",
    "order": 9,
    "pos": {
      "x": 3,
      "y": 3
    },
    "stake": 1,
    "omit": false,
    "config": {
      "remove_faces": true
    },
    "text": [
      "开局时",
      "玩家牌组中",
      "没有{C:attention}人头牌"
    ],
    "vars": []
  },
  {
    "key": "b_checkered",
    "enName": "Checkered Deck",
    "zhName": "方格牌组",
    "order": 10,
    "pos": {
      "x": 1,
      "y": 3
    },
    "stake": 1,
    "omit": false,
    "config": {},
    "text": [
      "开局时",
      "牌组中有{C:attention}26{C:spades}张黑桃{}和",
      "{C:attention}26{C:hearts}张红桃{}"
    ],
    "vars": []
  },
  {
    "key": "b_zodiac",
    "enName": "Zodiac Deck",
    "zhName": "黄道牌组",
    "order": 11,
    "pos": {
      "x": 3,
      "y": 4
    },
    "stake": 1,
    "omit": false,
    "config": {
      "vouchers": {
        "1": "v_tarot_merchant",
        "2": "v_planet_merchant",
        "3": "v_overstock_norm"
      }
    },
    "text": [
      "开局时即拥有",
      "{C:tarot,T:v_tarot_merchant}#1#{}、",
      "{C:planet,T:v_planet_merchant}#2#{}、",
      "和{C:attention,T:v_overstock_norm}#3#"
    ],
    "vars": [
      "塔罗牌商人",
      "星球牌商人",
      "库存过剩"
    ]
  },
  {
    "key": "b_painted",
    "enName": "Painted Deck",
    "zhName": "彩绘牌组",
    "order": 12,
    "pos": {
      "x": 4,
      "y": 3
    },
    "stake": 1,
    "omit": false,
    "config": {
      "hand_size": 2,
      "joker_slot": -1
    },
    "text": [
      "手牌上限{C:attention}+#1#{}",
      "小丑牌槽位{C:red}#2#{}"
    ],
    "vars": [
      2,
      -1
    ]
  },
  {
    "key": "b_anaglyph",
    "enName": "Anaglyph Deck",
    "zhName": "浮雕牌组",
    "order": 13,
    "pos": {
      "x": 2,
      "y": 4
    },
    "stake": 1,
    "omit": false,
    "config": {},
    "text": [
      "每次击败{C:attention}Boss盲注{}后",
      "获得一个{C:attention,T:tag_double}#1#"
    ],
    "vars": [
      "双倍标签"
    ]
  },
  {
    "key": "b_plasma",
    "enName": "Plasma Deck",
    "zhName": "等离子牌组",
    "order": 14,
    "pos": {
      "x": 4,
      "y": 2
    },
    "stake": 1,
    "omit": false,
    "config": {
      "ante_scaling": 2
    },
    "text": [
      "计算出牌分数时",
      "平衡{C:blue}筹码{}和{C:red}倍率{}",
      "盲注要求分数{C:red}X#1#{}"
    ],
    "vars": [
      2
    ]
  },
  {
    "key": "b_erratic",
    "enName": "Erratic Deck",
    "zhName": "古怪牌组",
    "order": 15,
    "pos": {
      "x": 2,
      "y": 3
    },
    "stake": 1,
    "omit": false,
    "config": {
      "randomize_rank_suit": true
    },
    "text": [
      "牌组中所有牌的",
      "{C:attention}点数{}和{C:attention}花色{}",
      "都是随机的"
    ],
    "vars": []
  },
  {
    "key": "b_challenge",
    "enName": "Challenge Deck",
    "zhName": "挑战牌组",
    "order": 16,
    "pos": {
      "x": 0,
      "y": 4
    },
    "stake": 1,
    "omit": true,
    "config": {},
    "text": [
      ""
    ],
    "vars": []
  }
];
