// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: game.lua P_CENTERS(m_* / e_*) / P_SEALS + globals.lua G.C + UI_definitions.lua G.BADGE_COL + Code/localization/zh_CN.lua
export interface EnhancementDef {
  key: string;
  enName: string;
  zhName: string;
  /** 卡面底图文件名：assets/enhancement/<image> */
  image: string;
  /** 存档 card.label（= center.label） */
  label: string;
  order: number;
  config: Record<string, number>;
  /** 标签底色（G.C.SECONDARY_SET.Enhanced，所有增强共用；游戏不改写此色，静态） */
  colour: string;
}

export interface SealDef {
  key: string;
  zhName: string;
  /** assets/seal/<image> */
  image: string;
  order: number;
  /** 标签底色（G.BADGE_COL.<key>_seal：金 GOLD / 红 RED / 蓝 BLUE / 紫 PURPLE；游戏不改写，静态） */
  colour: string;
}

export interface EditionDef {
  /** foil / holo / polychrome / negative：= shader 名（resources/shaders/<key>.fs）= 存档 card.edition 字段名 */
  key: string;
  enName: string;
  zhName: string;
  order: number;
  /** 中心 config，extra 为效果数值（由 core/saveDeck 按 set_edition 规则映射到 chips/mult/x_mult） */
  config: Record<string, number>;
  /** 标签底色的中位色（DARK_EDITION 呼吸的中点；降低动态/无法动画时使用） */
  colour: string;
}

/** 版本徽章底色的呼吸：游戏主循环每帧改写 G.C.DARK_EDITION（game.lua:2500-2502），
 *  R = base+amp*sin(w*t)、B = base+amp*(1-sin)、G = min(R,B)，周期 2π/w。四种版本共用同一色（同呼吸）。 */
export const EDITION_PULSE: { warm: string; mid: string; cool: string; period: number } = {"warm":"#cc9999","mid":"#9999cc","cool":"#6666ff","period":4.833};

export const ENHANCEMENTS: EnhancementDef[] = [
  {
    "key": "m_bonus",
    "enName": "Bonus",
    "zhName": "奖励牌",
    "image": "Bonus.png",
    "label": "Bonus Card",
    "order": 2,
    "config": {
      "bonus": 30
    },
    "colour": "#8389dd"
  },
  {
    "key": "m_mult",
    "enName": "Mult",
    "zhName": "倍率牌",
    "image": "Mult.png",
    "label": "Mult Card",
    "order": 3,
    "config": {
      "mult": 4
    },
    "colour": "#8389dd"
  },
  {
    "key": "m_wild",
    "enName": "Wild Card",
    "zhName": "万能牌",
    "image": "Wild Card.png",
    "label": "Wild Card",
    "order": 4,
    "config": {},
    "colour": "#8389dd"
  },
  {
    "key": "m_glass",
    "enName": "Glass Card",
    "zhName": "玻璃牌",
    "image": "Glass Card.png",
    "label": "Glass Card",
    "order": 5,
    "config": {
      "Xmult": 2,
      "extra": 4
    },
    "colour": "#8389dd"
  },
  {
    "key": "m_steel",
    "enName": "Steel Card",
    "zhName": "钢铁牌",
    "image": "Steel Card.png",
    "label": "Steel Card",
    "order": 6,
    "config": {
      "h_x_mult": 1.5
    },
    "colour": "#8389dd"
  },
  {
    "key": "m_stone",
    "enName": "Stone Card",
    "zhName": "石头牌",
    "image": "Stone Card.png",
    "label": "Stone Card",
    "order": 7,
    "config": {
      "bonus": 50
    },
    "colour": "#8389dd"
  },
  {
    "key": "m_gold",
    "enName": "Gold Card",
    "zhName": "黄金牌",
    "image": "Gold Card.png",
    "label": "Gold Card",
    "order": 8,
    "config": {
      "h_dollars": 3
    },
    "colour": "#8389dd"
  },
  {
    "key": "m_lucky",
    "enName": "Lucky Card",
    "zhName": "幸运牌",
    "image": "Lucky Card.png",
    "label": "Lucky Card",
    "order": 9,
    "config": {
      "mult": 20,
      "p_dollars": 20
    },
    "colour": "#8389dd"
  }
];

export const SEALS: SealDef[] = [
  {
    "key": "Gold",
    "zhName": "金色蜡封",
    "image": "Gold.png",
    "order": 1,
    "colour": "#eac058"
  },
  {
    "key": "Red",
    "zhName": "红色蜡封",
    "image": "Red.png",
    "order": 2,
    "colour": "#fe5f55"
  },
  {
    "key": "Blue",
    "zhName": "蓝色蜡封",
    "image": "Blue.png",
    "order": 3,
    "colour": "#009dff"
  },
  {
    "key": "Purple",
    "zhName": "紫色蜡封",
    "image": "Purple.png",
    "order": 4,
    "colour": "#8867a5"
  }
];

export const EDITIONS: EditionDef[] = [
  {
    "key": "foil",
    "enName": "Foil",
    "zhName": "闪箔",
    "order": 2,
    "config": {
      "extra": 50
    },
    "colour": "#9999cc"
  },
  {
    "key": "holo",
    "enName": "Holographic",
    "zhName": "镭射",
    "order": 3,
    "config": {
      "extra": 10
    },
    "colour": "#9999cc"
  },
  {
    "key": "polychrome",
    "enName": "Polychrome",
    "zhName": "多彩",
    "order": 4,
    "config": {
      "extra": 1.5
    },
    "colour": "#9999cc"
  },
  {
    "key": "negative",
    "enName": "Negative",
    "zhName": "负片",
    "order": 5,
    "config": {
      "extra": 1
    },
    "colour": "#9999cc"
  }
];
