// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: Code/game.lua P_CENTERS(c_*) / P_CENTER_POOLS + Code/localization/zh_CN.lua + globals.lua G.C.SECONDARY_SET
export type ConsumableSet = 'Tarot' | 'Planet' | 'Spectral';

export interface ConsumableDef {
  key: string;
  /** 英文名 = 素材文件名前缀（assets/{tarot|planet|spectral}/<enName>.png） */
  enName: string;
  zhName: string;
  set: ConsumableSet;
  order: number;
  /** 售价（塔罗/星球 3、幻灵 4）；开局持有实例的 sell_cost = floor(cost / 2) */
  cost: number;
  /** Tarots.png 图集坐标（10 列 × 6 行，格 142×190） */
  pos: { x: number; y: number };
  /** 素材文件名（保留原始空格） */
  image: string;
  /** 未解锁（灵魂 / 黑洞）：游戏内以占位图隐藏 */
  hidden: boolean;
  effect?: string;
  /** 中心 config，消耗牌效果参数的存档来源 */
  config: Record<string, unknown>;
  /** 中文描述行（原始文本，含 {C:xx} 标记与 #N# 占位符） */
  text: string[];
  /** #N# 取值（开局状态静态解析；序号未用到的位置不占位） */
  vars: (number | string)[];
  /** 分类色（G.C.SECONDARY_SET：塔罗紫 / 星球青 / 幻灵蓝） */
  colour: string;
}

export const CONSUMABLES: ConsumableDef[] = [
  {
    "key": "c_fool",
    "enName": "The Fool",
    "zhName": "愚者",
    "set": "Tarot",
    "order": 1,
    "cost": 3,
    "pos": {
      "x": 0,
      "y": 0
    },
    "image": "The Fool.png",
    "hidden": false,
    "effect": "Disable Blind Effect",
    "config": {},
    "text": [
      "生成本赛局中",
      "上一次使用的",
      "{C:tarot}塔罗牌{}或{C:planet}星球牌{}",
      "不包括{s:0.8,C:tarot}愚者{s:0.8}"
    ],
    "vars": [],
    "colour": "#a782d1"
  },
  {
    "key": "c_magician",
    "enName": "The Magician",
    "zhName": "魔术师",
    "set": "Tarot",
    "order": 2,
    "cost": 3,
    "pos": {
      "x": 1,
      "y": 0
    },
    "image": "The Magician.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_lucky",
      "max_highlighted": 2
    },
    "text": [
      "增强{C:attention}#1#{}张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      2,
      "幸运牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_high_priestess",
    "enName": "The High Priestess",
    "zhName": "女祭司",
    "set": "Tarot",
    "order": 3,
    "cost": 3,
    "pos": {
      "x": 2,
      "y": 0
    },
    "image": "The High Priestess.png",
    "hidden": false,
    "effect": "Round Bonus",
    "config": {
      "planets": 2
    },
    "text": [
      "生成最多{C:attention}#1#张",
      "张随机{C:planet}星球牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [
      2
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_empress",
    "enName": "The Empress",
    "zhName": "皇后",
    "set": "Tarot",
    "order": 4,
    "cost": 3,
    "pos": {
      "x": 3,
      "y": 0
    },
    "image": "The Empress.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_mult",
      "max_highlighted": 2
    },
    "text": [
      "增强{C:attention}#1#张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      2,
      "倍率牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_emperor",
    "enName": "The Emperor",
    "zhName": "皇帝",
    "set": "Tarot",
    "order": 5,
    "cost": 3,
    "pos": {
      "x": 4,
      "y": 0
    },
    "image": "The Emperor.png",
    "hidden": false,
    "effect": "Round Bonus",
    "config": {
      "tarots": 2
    },
    "text": [
      "生成最多{C:attention}#1#张",
      "随机{C:tarot}塔罗牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [
      2
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_heirophant",
    "enName": "The Hierophant",
    "zhName": "教皇",
    "set": "Tarot",
    "order": 6,
    "cost": 3,
    "pos": {
      "x": 5,
      "y": 0
    },
    "image": "The Hierophant.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_bonus",
      "max_highlighted": 2
    },
    "text": [
      "增强{C:attention}#1#张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      2,
      "奖励牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_lovers",
    "enName": "The Lovers",
    "zhName": "恋人",
    "set": "Tarot",
    "order": 7,
    "cost": 3,
    "pos": {
      "x": 6,
      "y": 0
    },
    "image": "The Lovers.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_wild",
      "max_highlighted": 1
    },
    "text": [
      "增强{C:attention}#1#{}张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      1,
      "万能牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_chariot",
    "enName": "The Chariot",
    "zhName": "战车",
    "set": "Tarot",
    "order": 8,
    "cost": 3,
    "pos": {
      "x": 7,
      "y": 0
    },
    "image": "The Chariot.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_steel",
      "max_highlighted": 1
    },
    "text": [
      "增强{C:attention}#1#{}张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      1,
      "钢铁牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_justice",
    "enName": "Justice",
    "zhName": "正义",
    "set": "Tarot",
    "order": 9,
    "cost": 3,
    "pos": {
      "x": 8,
      "y": 0
    },
    "image": "Justice.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_glass",
      "max_highlighted": 1
    },
    "text": [
      "增强{C:attention}#1#{}张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      1,
      "玻璃牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_hermit",
    "enName": "The Hermit",
    "zhName": "隐者",
    "set": "Tarot",
    "order": 10,
    "cost": 3,
    "pos": {
      "x": 9,
      "y": 0
    },
    "image": "The Hermit.png",
    "hidden": false,
    "effect": "Dollar Doubler",
    "config": {
      "extra": 20
    },
    "text": [
      "资金加倍",
      "{C:inactive}（最高{C:money}$#1#{C:inactive}）"
    ],
    "vars": [
      20
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_wheel_of_fortune",
    "enName": "The Wheel of Fortune",
    "zhName": "命运之轮",
    "set": "Tarot",
    "order": 11,
    "cost": 3,
    "pos": {
      "x": 0,
      "y": 1
    },
    "image": "The Wheel of Fortune.png",
    "hidden": false,
    "effect": "Round Bonus",
    "config": {
      "extra": 4
    },
    "text": [
      "有{C:green}#1#/#2#{}几率",
      "给一张随机{C:attention}小丑牌",
      "添加{C:dark_edition}闪箔{}、{C:dark_edition}镭射{}",
      "或{C:dark_edition}多彩{}版本"
    ],
    "vars": [
      1,
      4
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_strength",
    "enName": "Strength",
    "zhName": "力量",
    "set": "Tarot",
    "order": 12,
    "cost": 3,
    "pos": {
      "x": 1,
      "y": 1
    },
    "image": "Strength.png",
    "hidden": false,
    "effect": "Round Bonus",
    "config": {
      "mod_conv": "up_rank",
      "max_highlighted": 2
    },
    "text": [
      "将最多{C:attention}#1#{}张",
      "选定卡牌",
      "点数提高{C:attention}1"
    ],
    "vars": [
      2
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_hanged_man",
    "enName": "The Hanged Man",
    "zhName": "倒吊人",
    "set": "Tarot",
    "order": 13,
    "cost": 3,
    "pos": {
      "x": 2,
      "y": 1
    },
    "image": "The Hanged Man.png",
    "hidden": false,
    "effect": "Card Removal",
    "config": {
      "remove_card": true,
      "max_highlighted": 2
    },
    "text": [
      "摧毁最多{C:attention}#1#{}张",
      "选定卡牌"
    ],
    "vars": [
      2
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_death",
    "enName": "Death",
    "zhName": "死神",
    "set": "Tarot",
    "order": 14,
    "cost": 3,
    "pos": {
      "x": 3,
      "y": 1
    },
    "image": "Death.png",
    "hidden": false,
    "effect": "Card Conversion",
    "config": {
      "mod_conv": "card",
      "max_highlighted": 2,
      "min_highlighted": 2
    },
    "text": [
      "选定{C:attention}#1#{}张卡牌，",
      "将{C:attention}靠左{}的那张牌",
      "变成{C:attention}靠右{}的那张牌",
      "{C:inactive}（你可以拖动来改变位置）"
    ],
    "vars": [
      2
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_temperance",
    "enName": "Temperance",
    "zhName": "节制",
    "set": "Tarot",
    "order": 15,
    "cost": 3,
    "pos": {
      "x": 4,
      "y": 1
    },
    "image": "Temperance.png",
    "hidden": false,
    "effect": "Joker Payout",
    "config": {
      "extra": 50
    },
    "text": [
      "获得拥有的小丑牌",
      "售出价格总和的",
      "资金{C:inactive}（最高{C:money}$#1#{C:inactive}）",
      "{C:inactive}（当前{C:money}$#2#{C:inactive}）"
    ],
    "vars": [
      50,
      0
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_devil",
    "enName": "The Devil",
    "zhName": "恶魔",
    "set": "Tarot",
    "order": 16,
    "cost": 3,
    "pos": {
      "x": 5,
      "y": 1
    },
    "image": "The Devil.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_gold",
      "max_highlighted": 1
    },
    "text": [
      "增强{C:attention}#1#{}张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      1,
      "黄金牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_tower",
    "enName": "The Tower",
    "zhName": "塔",
    "set": "Tarot",
    "order": 17,
    "cost": 3,
    "pos": {
      "x": 6,
      "y": 1
    },
    "image": "The Tower.png",
    "hidden": false,
    "effect": "Enhance",
    "config": {
      "mod_conv": "m_stone",
      "max_highlighted": 1
    },
    "text": [
      "增强{C:attention}#1#{}张",
      "选定卡牌成为",
      "{C:attention}#2#"
    ],
    "vars": [
      1,
      "石头牌"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_star",
    "enName": "The Star",
    "zhName": "星星",
    "set": "Tarot",
    "order": 18,
    "cost": 3,
    "pos": {
      "x": 7,
      "y": 1
    },
    "image": "The Star.png",
    "hidden": false,
    "effect": "Suit Conversion",
    "config": {
      "suit_conv": "Diamonds",
      "max_highlighted": 3
    },
    "text": [
      "将最多{C:attention}#1#{}张",
      "选定卡牌",
      "转换为{V:1}#2#{}"
    ],
    "vars": [
      3,
      "方片"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_moon",
    "enName": "The Moon",
    "zhName": "月亮",
    "set": "Tarot",
    "order": 19,
    "cost": 3,
    "pos": {
      "x": 8,
      "y": 1
    },
    "image": "The Moon.png",
    "hidden": false,
    "effect": "Suit Conversion",
    "config": {
      "suit_conv": "Clubs",
      "max_highlighted": 3
    },
    "text": [
      "将最多{C:attention}#1#{}张",
      "选定卡牌",
      "转换为{V:1}#2#{}"
    ],
    "vars": [
      3,
      "梅花"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_sun",
    "enName": "The Sun",
    "zhName": "太阳",
    "set": "Tarot",
    "order": 20,
    "cost": 3,
    "pos": {
      "x": 9,
      "y": 1
    },
    "image": "The Sun.png",
    "hidden": false,
    "effect": "Suit Conversion",
    "config": {
      "suit_conv": "Hearts",
      "max_highlighted": 3
    },
    "text": [
      "将最多{C:attention}#1#{}张",
      "选定卡牌",
      "转换为{V:1}#2#{}"
    ],
    "vars": [
      3,
      "红桃"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_judgement",
    "enName": "Judgement",
    "zhName": "审判",
    "set": "Tarot",
    "order": 21,
    "cost": 3,
    "pos": {
      "x": 0,
      "y": 2
    },
    "image": "Judgement.png",
    "hidden": false,
    "effect": "Random Joker",
    "config": {},
    "text": [
      "生成一张随机的",
      "{C:attention}{}小丑牌",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [],
    "colour": "#a782d1"
  },
  {
    "key": "c_world",
    "enName": "The World",
    "zhName": "世界",
    "set": "Tarot",
    "order": 22,
    "cost": 3,
    "pos": {
      "x": 1,
      "y": 2
    },
    "image": "The World.png",
    "hidden": false,
    "effect": "Suit Conversion",
    "config": {
      "suit_conv": "Spades",
      "max_highlighted": 3
    },
    "text": [
      "将最多{C:attention}#1#{}张",
      "选定卡牌",
      "转换为{V:1}#2#{}"
    ],
    "vars": [
      3,
      "黑桃"
    ],
    "colour": "#a782d1"
  },
  {
    "key": "c_mercury",
    "enName": "Mercury",
    "zhName": "水星",
    "set": "Planet",
    "order": 1,
    "cost": 3,
    "pos": {
      "x": 0,
      "y": 3
    },
    "image": "Mercury.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Pair"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "对子",
      1,
      15
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_venus",
    "enName": "Venus",
    "zhName": "金星",
    "set": "Planet",
    "order": 2,
    "cost": 3,
    "pos": {
      "x": 1,
      "y": 3
    },
    "image": "Venus.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Three of a Kind"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "三条",
      2,
      20
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_earth",
    "enName": "Earth",
    "zhName": "地球",
    "set": "Planet",
    "order": 3,
    "cost": 3,
    "pos": {
      "x": 2,
      "y": 3
    },
    "image": "Earth.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Full House"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "葫芦",
      2,
      25
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_mars",
    "enName": "Mars",
    "zhName": "火星",
    "set": "Planet",
    "order": 4,
    "cost": 3,
    "pos": {
      "x": 3,
      "y": 3
    },
    "image": "Mars.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Four of a Kind"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "四条",
      3,
      30
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_jupiter",
    "enName": "Jupiter",
    "zhName": "木星",
    "set": "Planet",
    "order": 5,
    "cost": 3,
    "pos": {
      "x": 4,
      "y": 3
    },
    "image": "Jupiter.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Flush"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "同花",
      2,
      15
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_saturn",
    "enName": "Saturn",
    "zhName": "土星",
    "set": "Planet",
    "order": 6,
    "cost": 3,
    "pos": {
      "x": 5,
      "y": 3
    },
    "image": "Saturn.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Straight"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "顺子",
      3,
      30
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_uranus",
    "enName": "Uranus",
    "zhName": "天王星",
    "set": "Planet",
    "order": 7,
    "cost": 3,
    "pos": {
      "x": 6,
      "y": 3
    },
    "image": "Uranus.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Two Pair"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "两对",
      1,
      20
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_neptune",
    "enName": "Neptune",
    "zhName": "海王星",
    "set": "Planet",
    "order": 8,
    "cost": 3,
    "pos": {
      "x": 7,
      "y": 3
    },
    "image": "Neptune.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Straight Flush"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "同花顺",
      4,
      40
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_pluto",
    "enName": "Pluto",
    "zhName": "冥王星",
    "set": "Planet",
    "order": 9,
    "cost": 3,
    "pos": {
      "x": 8,
      "y": 3
    },
    "image": "Pluto.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "High Card"
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "高牌",
      1,
      10
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_planet_x",
    "enName": "Planet X",
    "zhName": "X行星",
    "set": "Planet",
    "order": 10,
    "cost": 3,
    "pos": {
      "x": 9,
      "y": 2
    },
    "image": "Planet X.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Five of a Kind",
      "softlock": true
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "五条",
      3,
      35
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_ceres",
    "enName": "Ceres",
    "zhName": "谷神星",
    "set": "Planet",
    "order": 11,
    "cost": 3,
    "pos": {
      "x": 8,
      "y": 2
    },
    "image": "Ceres.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Flush House",
      "softlock": true
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "同花葫芦",
      4,
      40
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_eris",
    "enName": "Eris",
    "zhName": "阋神星",
    "set": "Planet",
    "order": 12,
    "cost": 3,
    "pos": {
      "x": 3,
      "y": 2
    },
    "image": "Eris.png",
    "hidden": false,
    "effect": "Hand Upgrade",
    "config": {
      "hand_type": "Flush Five",
      "softlock": true
    },
    "text": [
      "{S:0.8}（{S:0.8,V:1}等级#1#{S:0.8}）{}",
      "升级{C:attention}#2#",
      "{C:mult}+#3#{}倍率并且",
      "{C:chips}+#4#{}筹码"
    ],
    "vars": [
      1,
      "同花五条",
      3,
      50
    ],
    "colour": "#13afce"
  },
  {
    "key": "c_familiar",
    "enName": "Familiar",
    "zhName": "使魔",
    "set": "Spectral",
    "order": 1,
    "cost": 4,
    "pos": {
      "x": 0,
      "y": 4
    },
    "image": "Familiar.png",
    "hidden": false,
    "config": {
      "remove_card": true,
      "extra": 3
    },
    "text": [
      "随机摧毁{C:attention}1{}张手牌",
      "并添加{C:attention}#1#{}张",
      "随机{C:attention}增强的人头牌{}",
      "到手牌中"
    ],
    "vars": [
      3
    ],
    "colour": "#4584fa"
  },
  {
    "key": "c_grim",
    "enName": "Grim",
    "zhName": "严峻",
    "set": "Spectral",
    "order": 2,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 4
    },
    "image": "Grim.png",
    "hidden": false,
    "config": {
      "remove_card": true,
      "extra": 2
    },
    "text": [
      "随机摧毁{C:attention}1{}张手牌",
      "并添加{C:attention}#1#{}张",
      "随机{C:attention}增强的A{}",
      "到手牌中"
    ],
    "vars": [
      2
    ],
    "colour": "#4584fa"
  },
  {
    "key": "c_incantation",
    "enName": "Incantation",
    "zhName": "咒语",
    "set": "Spectral",
    "order": 3,
    "cost": 4,
    "pos": {
      "x": 2,
      "y": 4
    },
    "image": "Incantation.png",
    "hidden": false,
    "config": {
      "remove_card": true,
      "extra": 4
    },
    "text": [
      "随机摧毁{C:attention}1{}张手牌",
      "并添加{C:attention}#1#{}张",
      "随机{C:attention}增强的数字牌{}",
      "到手牌中"
    ],
    "vars": [
      4
    ],
    "colour": "#4584fa"
  },
  {
    "key": "c_talisman",
    "enName": "Talisman",
    "zhName": "护身符",
    "set": "Spectral",
    "order": 4,
    "cost": 4,
    "pos": {
      "x": 3,
      "y": 4
    },
    "image": "Talisman.png",
    "hidden": false,
    "config": {
      "extra": "Gold",
      "max_highlighted": 1
    },
    "text": [
      "将{C:attention}金色蜡封{}添加到",
      "{C:attention}1{}张选定的",
      "手牌中"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_aura",
    "enName": "Aura",
    "zhName": "光环",
    "set": "Spectral",
    "order": 5,
    "cost": 4,
    "pos": {
      "x": 4,
      "y": 4
    },
    "image": "Aura.png",
    "hidden": false,
    "config": {},
    "text": [
      "选定{C:attention}1{}张手牌，为其添加",
      "{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}、或{C:dark_edition}多彩卡{}",
      "效果中的一种"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_wraith",
    "enName": "Wraith",
    "zhName": "幽灵",
    "set": "Spectral",
    "order": 6,
    "cost": 4,
    "pos": {
      "x": 5,
      "y": 4
    },
    "image": "Wraith.png",
    "hidden": false,
    "config": {},
    "text": [
      "生成一张随机的",
      "{C:red}稀有{C:attention}小丑牌{}",
      "将资金变为{C:money}$0"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_sigil",
    "enName": "Sigil",
    "zhName": "符印",
    "set": "Spectral",
    "order": 7,
    "cost": 4,
    "pos": {
      "x": 6,
      "y": 4
    },
    "image": "Sigil.png",
    "hidden": false,
    "config": {},
    "text": [
      "将手中所有",
      "卡牌转换为同一种",
      "随机{C:attention}花色"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_ouija",
    "enName": "Ouija",
    "zhName": "占卜",
    "set": "Spectral",
    "order": 8,
    "cost": 4,
    "pos": {
      "x": 7,
      "y": 4
    },
    "image": "Ouija.png",
    "hidden": false,
    "config": {},
    "text": [
      "将手中所有",
      "手持牌转换为同一个",
      "随机{C:attention}点数",
      "手牌上限{C:red}-1{}"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_ectoplasm",
    "enName": "Ectoplasm",
    "zhName": "灵质",
    "set": "Spectral",
    "order": 9,
    "cost": 4,
    "pos": {
      "x": 8,
      "y": 4
    },
    "image": "Ectoplasm.png",
    "hidden": false,
    "config": {},
    "text": [
      "添加{C:dark_edition}负片{}效果到",
      "一张随机的{C:attention}小丑牌",
      "手牌上限{C:red}-#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#4584fa"
  },
  {
    "key": "c_immolate",
    "enName": "Immolate",
    "zhName": "火祭",
    "set": "Spectral",
    "order": 10,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 4
    },
    "image": "Immolate.png",
    "hidden": false,
    "config": {
      "remove_card": true,
      "extra": {
        "destroy": 5,
        "dollars": 20
      }
    },
    "text": [
      "随机摧毁",
      "{C:attention}#1#{}张手牌",
      "获得{C:money}$#2#"
    ],
    "vars": [
      5,
      20
    ],
    "colour": "#4584fa"
  },
  {
    "key": "c_ankh",
    "enName": "Ankh",
    "zhName": "生命十字章",
    "set": "Spectral",
    "order": 11,
    "cost": 4,
    "pos": {
      "x": 0,
      "y": 5
    },
    "image": "Ankh.png",
    "hidden": false,
    "config": {
      "extra": 2
    },
    "text": [
      "随机复制一张",
      "{C:attention}小丑牌{}，摧毁",
      "其他小丑牌"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_deja_vu",
    "enName": "Deja Vu",
    "zhName": "既视感",
    "set": "Spectral",
    "order": 12,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 5
    },
    "image": "Deja Vu.png",
    "hidden": false,
    "config": {
      "extra": "Red",
      "max_highlighted": 1
    },
    "text": [
      "给你手牌中的",
      "{C:attention}1{}张所选卡牌",
      "加上{C:red}红色蜡封{}"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_hex",
    "enName": "Hex",
    "zhName": "妖法",
    "set": "Spectral",
    "order": 13,
    "cost": 4,
    "pos": {
      "x": 2,
      "y": 5
    },
    "image": "Hex.png",
    "hidden": false,
    "config": {
      "extra": 2
    },
    "text": [
      "随机为一张{C:attention}小丑牌{}添加",
      "{C:attention}多彩{}，摧毁",
      "其他小丑牌"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_trance",
    "enName": "Trance",
    "zhName": "入迷",
    "set": "Spectral",
    "order": 14,
    "cost": 4,
    "pos": {
      "x": 3,
      "y": 5
    },
    "image": "Trance.png",
    "hidden": false,
    "config": {
      "extra": "Blue",
      "max_highlighted": 1
    },
    "text": [
      "给你手牌中的",
      "{C:attention}1{}张所选卡牌",
      "加上{C:blue}蓝色蜡封{}"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_medium",
    "enName": "Medium",
    "zhName": "灵媒",
    "set": "Spectral",
    "order": 15,
    "cost": 4,
    "pos": {
      "x": 4,
      "y": 5
    },
    "image": "Medium.png",
    "hidden": false,
    "config": {
      "extra": "Purple",
      "max_highlighted": 1
    },
    "text": [
      "给你手牌中的",
      "{C:attention}1{}张所选卡牌",
      "加上{C:purple}紫色蜡封{}"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_cryptid",
    "enName": "Cryptid",
    "zhName": "神秘生物",
    "set": "Spectral",
    "order": 16,
    "cost": 4,
    "pos": {
      "x": 5,
      "y": 5
    },
    "image": "Cryptid.png",
    "hidden": false,
    "config": {
      "extra": 2,
      "max_highlighted": 1
    },
    "text": [
      "选定手牌中的{C:attention}1{}张牌",
      "生成{C:attention}#1#{}张其复制牌"
    ],
    "vars": [
      2
    ],
    "colour": "#4584fa"
  },
  {
    "key": "c_soul",
    "enName": "The Soul",
    "zhName": "灵魂",
    "set": "Spectral",
    "order": 17,
    "cost": 4,
    "pos": {
      "x": 2,
      "y": 2
    },
    "image": "The Soul.png",
    "hidden": true,
    "effect": "Unlocker",
    "config": {},
    "text": [
      "生成一张",
      "{C:legendary,E:1}传奇{}小丑牌",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [],
    "colour": "#4584fa"
  },
  {
    "key": "c_black_hole",
    "enName": "Black Hole",
    "zhName": "黑洞",
    "set": "Spectral",
    "order": 18,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 3
    },
    "image": "Black Hole.png",
    "hidden": true,
    "config": {},
    "text": [
      "所有{C:legendary,E:1}牌型",
      "提升{C:attention}1{}级"
    ],
    "vars": [],
    "colour": "#4584fa"
  }
];
