// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: Code/game.lua P_CENTERS(j_*) / Code/card.lua Joker UI 链 loc_vars + Code/localization/zh_CN.lua + globals.lua G.C.RARITY
export interface JokerDef {
  key: string;
  /** 英文名 = 素材文件名前缀（assets/joker/<enName>.png）= 存档 card.ability.name */
  enName: string;
  zhName: string;
  /** 稀有度 1-4（普通/罕见/稀有/传奇），页签分组与存档无直接关系，图鉴展示用 */
  rarity: number;
  order: number;
  /** 售价；开局持有实例的 sell_cost = floor(cost / 2) */
  cost: number;
  /** Jokers.png 图集坐标（10 列，格 142×190） */
  pos: { x: number; y: number };
  /** 素材文件名（保留原始空格） */
  image: string;
  /** 效果分组（如 "Suit Mult"）；中心未定义时缺省（存档不写 effect 键） */
  effect?: string;
  /** 中心 config，小丑效果参数的存档来源（数值在 extra / mult / t_mult 等字段） */
  config: Record<string, unknown>;
  /** 永恒贴纸兼容（card.lua:508 set_eternal 门控；false = 游戏拒绝该贴纸） */
  eternal_compat: boolean;
  /** 易腐贴纸兼容（card.lua:515 set_perishable 门控；false = 游戏拒绝该贴纸） */
  perishable_compat: boolean;
  /** 中文描述行（原始文本，含 {C:xx} 标记与 #N# 占位符） */
  text: string[];
  /** #N# 取值（开局状态静态解析；null = 不可静态取，对应描述行不显示） */
  vars: (number | string | null)[];
  /** 稀有度色（G.C.RARITY） */
  colour: string;
}

/** 贴纸中文名（zh_CN labels：永恒 / 易腐 / 租用） */
export const JOKER_STICKER_ZH: Record<string, string> = {"eternal":"永恒卡","perishable":"易腐","rental":"租用"};

/** 贴纸徽章色（globals.lua G.C：ETERNAL 玫红 / PERISHABLE 蓝紫 / RENTAL 金褐） */
export const JOKER_STICKER_COLOUR: Record<string, string> = {"eternal":"#c75985","perishable":"#4f5da1","rental":"#b18f43"};

/** 稀有度页签名（zh_CN k_common/k_uncommon/k_rare/k_legendary） */
export const JOKER_RARITY_ZH: Record<number, string> = {"1":"普通","2":"罕见","3":"稀有","4":"传奇"};

/** 稀有度配色（globals.lua G.C.RARITY：普通蓝 / 罕见绿 / 稀有红 / 传奇紫） */
export const JOKER_RARITY_COLOUR: Record<number, string> = {"1":"#009dff","2":"#4bc292","3":"#fe5f55","4":"#b26cbb"};

export const JOKERS: JokerDef[] = [
  {
    "key": "j_joker",
    "enName": "Joker",
    "zhName": "小丑",
    "rarity": 1,
    "order": 1,
    "cost": 2,
    "pos": {
      "x": 0,
      "y": 0
    },
    "image": "Joker.png",
    "effect": "Mult",
    "config": {
      "mult": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:red,s:1.1}+#1#{}倍率"
    ],
    "vars": [
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_greedy_joker",
    "enName": "Greedy Joker",
    "zhName": "贪婪小丑",
    "rarity": 1,
    "order": 2,
    "cost": 5,
    "pos": {
      "x": 6,
      "y": 1
    },
    "image": "Greedy Joker.png",
    "effect": "Suit Mult",
    "config": {
      "extra": {
        "s_mult": 3,
        "suit": "Diamonds"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:diamonds}#2#{}花色牌",
      "在计分时给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      3,
      "方片"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_lusty_joker",
    "enName": "Lusty Joker",
    "zhName": "色欲小丑",
    "rarity": 1,
    "order": 3,
    "cost": 5,
    "pos": {
      "x": 7,
      "y": 1
    },
    "image": "Lusty Joker.png",
    "effect": "Suit Mult",
    "config": {
      "extra": {
        "s_mult": 3,
        "suit": "Hearts"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:hearts}#2#{}花色牌",
      "在计分时给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      3,
      "红桃"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_wrathful_joker",
    "enName": "Wrathful Joker",
    "zhName": "愤怒小丑",
    "rarity": 1,
    "order": 4,
    "cost": 5,
    "pos": {
      "x": 8,
      "y": 1
    },
    "image": "Wrathful Joker.png",
    "effect": "Suit Mult",
    "config": {
      "extra": {
        "s_mult": 3,
        "suit": "Spades"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:spades}#2#{}花色牌",
      "在计分时给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      3,
      "黑桃"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_gluttenous_joker",
    "enName": "Gluttonous Joker",
    "zhName": "暴食小丑",
    "rarity": 1,
    "order": 5,
    "cost": 5,
    "pos": {
      "x": 9,
      "y": 1
    },
    "image": "Gluttonous Joker.png",
    "effect": "Suit Mult",
    "config": {
      "extra": {
        "s_mult": 3,
        "suit": "Clubs"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:clubs}#2#{}花色牌",
      "在计分时给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      3,
      "梅花"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_jolly",
    "enName": "Jolly Joker",
    "zhName": "开心小丑",
    "rarity": 1,
    "order": 6,
    "cost": 3,
    "pos": {
      "x": 2,
      "y": 0
    },
    "image": "Jolly Joker.png",
    "effect": "Type Mult",
    "config": {
      "t_mult": 8,
      "type": "Pair"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#{}",
      "{C:red}+#1#{}倍率"
    ],
    "vars": [
      8,
      "对子"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_zany",
    "enName": "Zany Joker",
    "zhName": "古怪小丑",
    "rarity": 1,
    "order": 7,
    "cost": 4,
    "pos": {
      "x": 3,
      "y": 0
    },
    "image": "Zany Joker.png",
    "effect": "Type Mult",
    "config": {
      "t_mult": 12,
      "type": "Three of a Kind"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#{}",
      "{C:red}+#1#{}倍率"
    ],
    "vars": [
      12,
      "三条"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_mad",
    "enName": "Mad Joker",
    "zhName": "疯狂小丑",
    "rarity": 1,
    "order": 8,
    "cost": 4,
    "pos": {
      "x": 4,
      "y": 0
    },
    "image": "Mad Joker.png",
    "effect": "Type Mult",
    "config": {
      "t_mult": 10,
      "type": "Two Pair"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#{}",
      "{C:red}+#1#{}倍率"
    ],
    "vars": [
      10,
      "两对"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_crazy",
    "enName": "Crazy Joker",
    "zhName": "狂野小丑",
    "rarity": 1,
    "order": 9,
    "cost": 4,
    "pos": {
      "x": 5,
      "y": 0
    },
    "image": "Crazy Joker.png",
    "effect": "Type Mult",
    "config": {
      "t_mult": 12,
      "type": "Straight"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#{}",
      "{C:red}+#1#{}倍率"
    ],
    "vars": [
      12,
      "顺子"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_droll",
    "enName": "Droll Joker",
    "zhName": "滑稽小丑",
    "rarity": 1,
    "order": 10,
    "cost": 4,
    "pos": {
      "x": 6,
      "y": 0
    },
    "image": "Droll Joker.png",
    "effect": "Type Mult",
    "config": {
      "t_mult": 10,
      "type": "Flush"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#{}",
      "{C:red}+#1#{}倍率"
    ],
    "vars": [
      10,
      "同花"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_sly",
    "enName": "Sly Joker",
    "zhName": "奸诈小丑",
    "rarity": 1,
    "order": 11,
    "cost": 3,
    "pos": {
      "x": 0,
      "y": 14
    },
    "image": "Sly Joker.png",
    "config": {
      "t_chips": 50,
      "type": "Pair"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{C:chips}+#1#{}筹码"
    ],
    "vars": [
      50,
      "对子"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_wily",
    "enName": "Wily Joker",
    "zhName": "狡猾小丑",
    "rarity": 1,
    "order": 12,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 14
    },
    "image": "Wily Joker.png",
    "config": {
      "t_chips": 100,
      "type": "Three of a Kind"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{C:chips}+#1#{}筹码"
    ],
    "vars": [
      100,
      "三条"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_clever",
    "enName": "Clever Joker",
    "zhName": "聪敏小丑",
    "rarity": 1,
    "order": 13,
    "cost": 4,
    "pos": {
      "x": 2,
      "y": 14
    },
    "image": "Clever Joker.png",
    "config": {
      "t_chips": 80,
      "type": "Two Pair"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{C:chips}+#1#{}筹码"
    ],
    "vars": [
      80,
      "两对"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_devious",
    "enName": "Devious Joker",
    "zhName": "阴险小丑",
    "rarity": 1,
    "order": 14,
    "cost": 4,
    "pos": {
      "x": 3,
      "y": 14
    },
    "image": "Devious Joker.png",
    "config": {
      "t_chips": 100,
      "type": "Straight"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{C:chips}+#1#{}筹码"
    ],
    "vars": [
      100,
      "顺子"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_crafty",
    "enName": "Crafty Joker",
    "zhName": "精明小丑",
    "rarity": 1,
    "order": 15,
    "cost": 4,
    "pos": {
      "x": 4,
      "y": 14
    },
    "image": "Crafty Joker.png",
    "config": {
      "t_chips": 80,
      "type": "Flush"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{C:chips}+#1#{}筹码"
    ],
    "vars": [
      80,
      "同花"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_half",
    "enName": "Half Joker",
    "zhName": "半张小丑",
    "rarity": 1,
    "order": 16,
    "cost": 5,
    "pos": {
      "x": 7,
      "y": 0
    },
    "image": "Half Joker.png",
    "effect": "Hand Size Mult",
    "config": {
      "extra": {
        "mult": 20,
        "size": 3
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌",
      "少于等于{C:attention}#2#{}张",
      "{C:red}+#1#{}倍率"
    ],
    "vars": [
      20,
      3
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_stencil",
    "enName": "Joker Stencil",
    "zhName": "模具小丑",
    "rarity": 2,
    "order": 17,
    "cost": 8,
    "pos": {
      "x": 2,
      "y": 5
    },
    "image": "Joker Stencil.png",
    "effect": "Hand Size Mult",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每个空的{C:attention}小丑牌{}槽位",
      "获得{X:red,C:white} X1{}倍率",
      "{s:0.8}模具小丑算作空位",
      "（当前为{X:red,C:white} X#1# {C:inactive}）"
    ],
    "vars": [
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_four_fingers",
    "enName": "Four Fingers",
    "zhName": "四指",
    "rarity": 2,
    "order": 18,
    "cost": 7,
    "pos": {
      "x": 6,
      "y": 6
    },
    "image": "Four Fingers.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "所有{C:attention}同花{}和",
      "{C:attention}顺子{}都可以",
      "由{C:attention}4{}张牌组成"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_mime",
    "enName": "Mime",
    "zhName": "哑剧演员",
    "rarity": 2,
    "order": 19,
    "cost": 5,
    "pos": {
      "x": 4,
      "y": 1
    },
    "image": "Mime.png",
    "effect": "Hand card double",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "重新触发所有",
      "{C:attention}留在手牌中的",
      "{C:attention}牌{}的能力"
    ],
    "vars": [
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_credit_card",
    "enName": "Credit Card",
    "zhName": "信用卡",
    "rarity": 1,
    "order": 20,
    "cost": 1,
    "pos": {
      "x": 5,
      "y": 1
    },
    "image": "Credit Card.png",
    "effect": "Credit",
    "config": {
      "extra": 20
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "可以负债",
      "最多{C:red}-$#1#{}"
    ],
    "vars": [
      20
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_ceremonial",
    "enName": "Ceremonial Dagger",
    "zhName": "仪式匕首",
    "rarity": 2,
    "order": 21,
    "cost": 6,
    "pos": {
      "x": 5,
      "y": 5
    },
    "image": "Ceremonial Dagger.png",
    "effect": "",
    "config": {
      "mult": 0
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "在选择{C:attention}盲注{}时",
      "摧毁右侧的小丑牌",
      "并将其售价的{C:attention}两倍",
      "永久添加至这张牌的{C:attention}倍率",
      "{C:inactive}（当前为{C:mult}+#1#{C:inactive}倍）"
    ],
    "vars": [
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_banner",
    "enName": "Banner",
    "zhName": "旗帜",
    "rarity": 1,
    "order": 22,
    "cost": 5,
    "pos": {
      "x": 1,
      "y": 2
    },
    "image": "Banner.png",
    "effect": "Discard Chips",
    "config": {
      "extra": 30
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每一个剩余的",
      "{C:attention}弃牌{}次数",
      "{C:chips}+#1#{}筹码"
    ],
    "vars": [
      30
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_mystic_summit",
    "enName": "Mystic Summit",
    "zhName": "神秘之峰",
    "rarity": 1,
    "order": 23,
    "cost": 5,
    "pos": {
      "x": 2,
      "y": 2
    },
    "image": "Mystic Summit.png",
    "effect": "No Discard Mult",
    "config": {
      "extra": {
        "mult": 15,
        "d_remaining": 0
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "当剩余{C:attention}#2#{}次",
      "弃牌次数",
      "{C:mult}+#1#{}倍率"
    ],
    "vars": [
      15,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_marble",
    "enName": "Marble Joker",
    "zhName": "大理石小丑",
    "rarity": 2,
    "order": 24,
    "cost": 6,
    "pos": {
      "x": 3,
      "y": 2
    },
    "image": "Marble Joker.png",
    "effect": "Stone card hands",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "选择{C:attention}盲注{}后",
      "牌组中会添加",
      "一张{C:attention}石头{}牌"
    ],
    "vars": [
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_loyalty_card",
    "enName": "Loyalty Card",
    "zhName": "积分卡",
    "rarity": 2,
    "order": 25,
    "cost": 5,
    "pos": {
      "x": 4,
      "y": 2
    },
    "image": "Loyalty Card.png",
    "effect": "1 in 10 mult",
    "config": {
      "extra": {
        "Xmult": 4,
        "every": 5,
        "remaining": "5 remaining"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每第{C:attention}#2#{}次出牌时",
      "给予{X:red,C:white} X#1# {}倍率",
      "{C:inactive}（#3#）"
    ],
    "vars": [
      4,
      6,
      null
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_8_ball",
    "enName": "8 Ball",
    "zhName": "八号球",
    "rarity": 1,
    "order": 26,
    "cost": 5,
    "pos": {
      "x": 0,
      "y": 5
    },
    "image": "8 Ball.png",
    "effect": "Spawn Tarot",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的每一张{C:attention}8{}",
      "有{C:green}#1#/#2#{}几率在计分时",
      "生成一张{C:tarot}塔罗牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [
      1,
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_misprint",
    "enName": "Misprint",
    "zhName": "印错小丑",
    "rarity": 1,
    "order": 27,
    "cost": 4,
    "pos": {
      "x": 6,
      "y": 2
    },
    "image": "Misprint.png",
    "effect": "Random Mult",
    "config": {
      "extra": {
        "max": 23,
        "min": 0
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      ""
    ],
    "vars": [
      23,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_dusk",
    "enName": "Dusk",
    "zhName": "黄昏",
    "rarity": 2,
    "order": 28,
    "cost": 5,
    "pos": {
      "x": 4,
      "y": 7
    },
    "image": "Dusk.png",
    "effect": "",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每回合的",
      "{C:attention}最后一次出牌{}时",
      "所有打出的牌会被触发两次"
    ],
    "vars": [
      2
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_raised_fist",
    "enName": "Raised Fist",
    "zhName": "致胜之拳",
    "rarity": 1,
    "order": 29,
    "cost": 5,
    "pos": {
      "x": 8,
      "y": 2
    },
    "image": "Raised Fist.png",
    "effect": "Socialized Mult",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "将留在手牌中点数{C:attention}最小{}牌",
      "点数的{C:attention}两倍{}",
      "加到倍率上"
    ],
    "vars": [],
    "colour": "#009dff"
  },
  {
    "key": "j_chaos",
    "enName": "Chaos the Clown",
    "zhName": "混沌小丑",
    "rarity": 1,
    "order": 30,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 0
    },
    "image": "Chaos the Clown.png",
    "effect": "Bonus Rerolls",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每次商店",
      "{C:green}#1#{}次免费重掷"
    ],
    "vars": [
      1
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_fibonacci",
    "enName": "Fibonacci",
    "zhName": "斐波那契",
    "rarity": 2,
    "order": 31,
    "cost": 8,
    "pos": {
      "x": 1,
      "y": 5
    },
    "image": "Fibonacci.png",
    "effect": "Card Mult",
    "config": {
      "extra": 8
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的每一张",
      "{C:attention}A{}、{C:attention}2{}、{C:attention}3{}、{C:attention}5{}、{C:attention}8{}",
      "在计分时给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      8
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_steel_joker",
    "enName": "Steel Joker",
    "zhName": "钢铁小丑",
    "rarity": 2,
    "order": 32,
    "cost": 7,
    "pos": {
      "x": 7,
      "y": 2
    },
    "image": "Steel Joker.png",
    "effect": "Steel Card Buff",
    "config": {
      "extra": 0.2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:attention}完整牌组{}内每有一张",
      "{C:attention}钢铁牌{}",
      "给予{X:mult,C:white} X#1# {}倍率",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.2,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_scary_face",
    "enName": "Scary Face",
    "zhName": "恐怖面孔",
    "rarity": 1,
    "order": 33,
    "cost": 4,
    "pos": {
      "x": 2,
      "y": 3
    },
    "image": "Scary Face.png",
    "effect": "Scary Face Cards",
    "config": {
      "extra": 30
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{C:attention}人头牌{}",
      "在计分时",
      "给予{C:chips}+#1#{}筹码"
    ],
    "vars": [
      30
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_abstract",
    "enName": "Abstract Joker",
    "zhName": "抽象小丑",
    "rarity": 1,
    "order": 34,
    "cost": 4,
    "pos": {
      "x": 3,
      "y": 3
    },
    "image": "Abstract Joker.png",
    "effect": "Joker Mult",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每有一张{C:attention}小丑牌{}",
      "{C:mult}+#1#{}倍率",
      "{C:inactive}（当前为{C:red}+#2#{C:inactive}倍率）"
    ],
    "vars": [
      3,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_delayed_grat",
    "enName": "Delayed Gratification",
    "zhName": "延迟满足",
    "rarity": 1,
    "order": 35,
    "cost": 4,
    "pos": {
      "x": 4,
      "y": 3
    },
    "image": "Delayed Gratification.png",
    "effect": "Discard dollars",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果在回合结束时",
      "没有使用弃牌，则每把{C:attention}弃牌{}",
      "获得{C:money}$#1#{}"
    ],
    "vars": [
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_hack",
    "enName": "Hack",
    "zhName": "烂脱口秀演员",
    "rarity": 2,
    "order": 36,
    "cost": 6,
    "pos": {
      "x": 5,
      "y": 2
    },
    "image": "Hack.png",
    "effect": "Low Card double",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "重新触发",
      "所有打出的",
      "{C:attention}2{}、{C:attention}3{}、{C:attention}4{}和{C:attention}5{}"
    ],
    "vars": [
      2
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_pareidolia",
    "enName": "Pareidolia",
    "zhName": "幻视",
    "rarity": 2,
    "order": 37,
    "cost": 5,
    "pos": {
      "x": 6,
      "y": 3
    },
    "image": "Pareidolia.png",
    "effect": "All face cards",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "所有卡牌",
      "均视为",
      "{C:attention}人头牌{}"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_gros_michel",
    "enName": "Gros Michel",
    "zhName": "大麦克香蕉",
    "rarity": 1,
    "order": 38,
    "cost": 5,
    "pos": {
      "x": 7,
      "y": 6
    },
    "image": "Gros Michel.png",
    "effect": "",
    "config": {
      "extra": {
        "odds": 6,
        "mult": 15
      }
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "{C:mult}+#1#{}倍率",
      "回合结束时",
      "有{C:green}#2#/#3#{}的几率",
      "摧毁此牌"
    ],
    "vars": [
      15,
      1,
      6
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_even_steven",
    "enName": "Even Steven",
    "zhName": "偶数史蒂文",
    "rarity": 1,
    "order": 39,
    "cost": 4,
    "pos": {
      "x": 8,
      "y": 3
    },
    "image": "Even Steven.png",
    "effect": "Even Card Buff",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的点数为",
      "{C:attention}偶数{}的牌",
      "在计分时给予{C:mult}+#1#{}倍率",
      "{C:inactive}（10、8、6、4、2）"
    ],
    "vars": [
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_odd_todd",
    "enName": "Odd Todd",
    "zhName": "奇数托德",
    "rarity": 1,
    "order": 40,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 3
    },
    "image": "Odd Todd.png",
    "effect": "Odd Card Buff",
    "config": {
      "extra": 31
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的点数为",
      "{C:attention}奇数{}的牌",
      "在计分时给予{C:chips}+#1#{}筹码",
      "{C:inactive}（A、9、7、5、3）"
    ],
    "vars": [
      31
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_scholar",
    "enName": "Scholar",
    "zhName": "学者",
    "rarity": 1,
    "order": 41,
    "cost": 4,
    "pos": {
      "x": 0,
      "y": 4
    },
    "image": "Scholar.png",
    "effect": "Ace Buff",
    "config": {
      "extra": {
        "mult": 4,
        "chips": 20
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{C:attention}A{}牌",
      "在计分时给予",
      "{C:mult}+#1#{}倍率",
      "和{C:chips}+#2#{}筹码"
    ],
    "vars": [
      4,
      20
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_business",
    "enName": "Business Card",
    "zhName": "名片",
    "rarity": 1,
    "order": 42,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 4
    },
    "image": "Business Card.png",
    "effect": "Face Card dollar Chance",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{C:attention}人头牌{}在计分时",
      "有{C:green}#1#/#2#{}的几率",
      "获得{C:money}$2{}"
    ],
    "vars": [
      1,
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_supernova",
    "enName": "Supernova",
    "zhName": "超新星",
    "rarity": 1,
    "order": 43,
    "cost": 5,
    "pos": {
      "x": 2,
      "y": 4
    },
    "image": "Supernova.png",
    "effect": "Hand played mult",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "将{C:attention}牌型{}在本赛局内",
      "被{C:attention}打出过{}的次数",
      "添加至倍率"
    ],
    "vars": [
      1
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_ride_the_bus",
    "enName": "Ride the Bus",
    "zhName": "搭乘巴士",
    "rarity": 1,
    "order": 44,
    "cost": 6,
    "pos": {
      "x": 1,
      "y": 6
    },
    "image": "Ride the Bus.png",
    "effect": "",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "连续打出没有",
      "计分{C:attention}人头牌{}的牌时",
      "这张小丑牌获得{C:mult}+#1#{}倍率",
      "失败将会重置倍率",
      "{C:inactive}（当前为{C:mult}+#2#{C:inactive}倍率）"
    ],
    "vars": [
      1,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_space",
    "enName": "Space Joker",
    "zhName": "太空小丑",
    "rarity": 2,
    "order": 45,
    "cost": 5,
    "pos": {
      "x": 3,
      "y": 5
    },
    "image": "Space Joker.png",
    "effect": "Upgrade Hand chance",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "有{C:green}#1#/#2#{}的",
      "几率升级",
      "打出的{C:attention}牌型等级{}"
    ],
    "vars": [
      1,
      4
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_egg",
    "enName": "Egg",
    "zhName": "鸡蛋",
    "rarity": 1,
    "order": 46,
    "cost": 4,
    "pos": {
      "x": 0,
      "y": 10
    },
    "image": "Egg.png",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在回合结束时",
      "本卡的{c:attention}出售价值",
      "增加{c:money}$#1#"
    ],
    "vars": [
      3
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_burglar",
    "enName": "Burglar",
    "zhName": "窃贼",
    "rarity": 2,
    "order": 47,
    "cost": 6,
    "pos": {
      "x": 1,
      "y": 10
    },
    "image": "Burglar.png",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "选择{C:attention}盲注{}后",
      "出牌次数{C:red}+#1#{}，并",
      "{C:attention}失去所有弃牌次数"
    ],
    "vars": [
      3
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_blackboard",
    "enName": "Blackboard",
    "zhName": "黑板",
    "rarity": 2,
    "order": 48,
    "cost": 6,
    "pos": {
      "x": 2,
      "y": 10
    },
    "image": "Blackboard.png",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果留在手牌中的",
      "所有牌都是{C:spades}#2#{}或{C:clubs}#3#{}",
      "则{X:red,C:white} X#1# {}倍率"
    ],
    "vars": [
      3,
      "黑桃",
      "梅花"
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_runner",
    "enName": "Runner",
    "zhName": "跑步选手",
    "rarity": 1,
    "order": 49,
    "cost": 5,
    "pos": {
      "x": 3,
      "y": 10
    },
    "image": "Runner.png",
    "config": {
      "extra": {
        "chips": 0,
        "chip_mod": 15
      }
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "如果打出的牌中包含",
      "{C:attention}顺子{}",
      "这张小丑获得{C:chips}+#2#{}筹码",
      "{C:inactive}（当前为{C:chips}+#1#{C:inactive}筹码）"
    ],
    "vars": [
      0,
      15
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_ice_cream",
    "enName": "Ice Cream",
    "zhName": "冰淇淋",
    "rarity": 1,
    "order": 50,
    "cost": 5,
    "pos": {
      "x": 4,
      "y": 10
    },
    "image": "Ice Cream.png",
    "config": {
      "extra": {
        "chips": 100,
        "chip_mod": 5
      }
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "{C:chips}+#1#{}筹码",
      "每次出牌后",
      "{C:chips}-#2#{}筹码"
    ],
    "vars": [
      100,
      5
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_dna",
    "enName": "DNA",
    "zhName": "DNA",
    "rarity": 3,
    "order": 51,
    "cost": 8,
    "pos": {
      "x": 5,
      "y": 10
    },
    "image": "DNA.png",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果回合的{C:attention}第一次出牌{}",
      "只有{C:attention}1{}张牌，则将其",
      "永久复制到牌组，并将",
      "复制牌放到{C:attention}手牌中"
    ],
    "vars": [
      null
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_splash",
    "enName": "Splash",
    "zhName": "飞溅",
    "rarity": 1,
    "order": 52,
    "cost": 3,
    "pos": {
      "x": 6,
      "y": 10
    },
    "image": "Splash.png",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每张{C:attention}打出的牌",
      "都可以计分"
    ],
    "vars": [],
    "colour": "#009dff"
  },
  {
    "key": "j_blue_joker",
    "enName": "Blue Joker",
    "zhName": "蓝色小丑",
    "rarity": 1,
    "order": 53,
    "cost": 5,
    "pos": {
      "x": 7,
      "y": 10
    },
    "image": "Blue Joker.png",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每张{C:attention}牌组{}内剩余",
      "的卡牌，{C:chips}+#1#{}筹码",
      "{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）"
    ],
    "vars": [
      2,
      104
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_sixth_sense",
    "enName": "Sixth Sense",
    "zhName": "第六感",
    "rarity": 2,
    "order": 54,
    "cost": 6,
    "pos": {
      "x": 8,
      "y": 10
    },
    "image": "Sixth Sense.png",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果回合的{C:attention}第一次出牌{}",
      "是一张单独的{C:attention}6{}",
      "则将其销毁并生成一张{C:spectral}幻灵牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_constellation",
    "enName": "Constellation",
    "zhName": "星座",
    "rarity": 2,
    "order": 55,
    "cost": 6,
    "pos": {
      "x": 9,
      "y": 10
    },
    "image": "Constellation.png",
    "config": {
      "extra": 0.1,
      "Xmult": 1
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每使用一张{C:planet}星球牌{}",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.1,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_hiker",
    "enName": "Hiker",
    "zhName": "徒步者",
    "rarity": 2,
    "order": 56,
    "cost": 5,
    "pos": {
      "x": 0,
      "y": 11
    },
    "image": "Hiker.png",
    "config": {
      "extra": 5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的每一张牌",
      "在{c:attention}计分{}时",
      "会永久获得{C:chips}+#1#{}筹码"
    ],
    "vars": [
      5
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_faceless",
    "enName": "Faceless Joker",
    "zhName": "无面小丑",
    "rarity": 1,
    "order": 57,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 11
    },
    "image": "Faceless Joker.png",
    "config": {
      "extra": {
        "dollars": 5,
        "faces": 3
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果同时弃掉",
      "{C:attention}#2#{}张或更多张",
      "{C:attention}人头牌{}",
      "获得{C:money}$#1#{}"
    ],
    "vars": [
      5,
      3
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_green_joker",
    "enName": "Green Joker",
    "zhName": "绿色小丑",
    "rarity": 1,
    "order": 58,
    "cost": 4,
    "pos": {
      "x": 2,
      "y": 11
    },
    "image": "Green Joker.png",
    "config": {
      "extra": {
        "hand_add": 1,
        "discard_sub": 1
      }
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每次出牌，这张小丑牌{C:mult}+#1#{}倍率",
      "每次弃牌，这张小丑牌{C:mult}-#2#{}倍率",
      "{C:inactive}（当前为{C:mult}+#3#{C:inactive}倍）"
    ],
    "vars": [
      1,
      1,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_superposition",
    "enName": "Superposition",
    "zhName": "叠加态",
    "rarity": 1,
    "order": 59,
    "cost": 4,
    "pos": {
      "x": 3,
      "y": 11
    },
    "image": "Superposition.png",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中包含",
      "一张{C:attention}A{}和一个{C:attention}顺子{}",
      "生成一张{C:tarot}塔罗牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [
      null
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_todo_list",
    "enName": "To Do List",
    "zhName": "待办清单",
    "rarity": 1,
    "order": 60,
    "cost": 4,
    "pos": {
      "x": 4,
      "y": 11
    },
    "image": "To Do List.png",
    "config": {
      "extra": {
        "dollars": 4,
        "poker_hand": "High Card"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果{C:attention}出牌牌型{}为{C:attention}#2#{}",
      "获得{C:money}$#1#{}",
      "每回合结束时",
      "牌型都会改变"
    ],
    "vars": [
      4,
      "高牌"
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_cavendish",
    "enName": "Cavendish",
    "zhName": "卡文迪什",
    "rarity": 1,
    "order": 61,
    "cost": 4,
    "pos": {
      "x": 5,
      "y": 11
    },
    "image": "Cavendish.png",
    "config": {
      "extra": {
        "odds": 1000,
        "Xmult": 3
      }
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "{X:mult,C:white}X#1#{}倍率",
      "回合结束时",
      "有{C:green}#2#/#3#{}的几率",
      "摧毁此牌"
    ],
    "vars": [
      3,
      1,
      1000
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_card_sharp",
    "enName": "Card Sharp",
    "zhName": "老千小丑",
    "rarity": 2,
    "order": 62,
    "cost": 6,
    "pos": {
      "x": 6,
      "y": 11
    },
    "image": "Card Sharp.png",
    "config": {
      "extra": {
        "Xmult": 3
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的{C:attention}牌型{}已经",
      "在本回合打出过",
      "则{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      3
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_red_card",
    "enName": "Red Card",
    "zhName": "红牌",
    "rarity": 1,
    "order": 63,
    "cost": 5,
    "pos": {
      "x": 7,
      "y": 11
    },
    "image": "Red Card.png",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "当跳过任一{C:attention}补充包{}时",
      "这张小丑牌获得{C:red}+#1#{}倍率",
      "{C:inactive}（当前为{C:red}+#2#{C:inactive}倍率）"
    ],
    "vars": [
      3,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_madness",
    "enName": "Madness",
    "zhName": "疯狂",
    "rarity": 2,
    "order": 64,
    "cost": 7,
    "pos": {
      "x": 8,
      "y": 11
    },
    "image": "Madness.png",
    "config": {
      "extra": 0.5
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "在{C:attention}小盲注{}或{C:attention}大盲注{}被选中时",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "然后随机{C:attention}摧毁{}一张小丑牌",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{}倍率）"
    ],
    "vars": [
      0.5,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_square",
    "enName": "Square Joker",
    "zhName": "方形小丑",
    "rarity": 1,
    "order": 65,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 11
    },
    "image": "Square Joker.png",
    "config": {
      "extra": {
        "chips": 0,
        "chip_mod": 4
      }
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "如果打出的牌",
      "正好是{C:attention}4{}张牌",
      "这张小丑牌获得{C:chips}+#2#{}筹码",
      "{C:inactive}（当前为{C:chips}+#1#{C:inactive}筹码）"
    ],
    "vars": [
      0,
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_seance",
    "enName": "Seance",
    "zhName": "通灵",
    "rarity": 2,
    "order": 66,
    "cost": 6,
    "pos": {
      "x": 0,
      "y": 12
    },
    "image": "Seance.png",
    "config": {
      "extra": {
        "poker_hand": "Straight Flush"
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果{C:attention}牌型{}为",
      "{C:attention}#1#{}，随机生成",
      "一张{C:spectral}幻灵牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [
      "同花顺"
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_riff_raff",
    "enName": "Riff-raff",
    "zhName": "乌合之众",
    "rarity": 1,
    "order": 67,
    "cost": 6,
    "pos": {
      "x": 1,
      "y": 12
    },
    "image": "Riff-raff.png",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在选择{C:attention}盲注{}时",
      "生成{C:attention}#1#张{C:blue}普通{C:attention}小丑牌",
      "{C:inactive}（必须有空间）"
    ],
    "vars": [
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_vampire",
    "enName": "Vampire",
    "zhName": "吸血鬼",
    "rarity": 2,
    "order": 68,
    "cost": 7,
    "pos": {
      "x": 2,
      "y": 12
    },
    "image": "Vampire.png",
    "config": {
      "extra": 0.1,
      "Xmult": 1
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每打出一张计分的{C:attention}增强卡牌{}",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "并移除卡牌的{C:attention}增强效果",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.1,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_shortcut",
    "enName": "Shortcut",
    "zhName": "捷径",
    "rarity": 2,
    "order": 69,
    "cost": 7,
    "pos": {
      "x": 3,
      "y": 12
    },
    "image": "Shortcut.png",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "让{C:attention}顺子{}可以",
      "相隔{C:attention}1个点数{}组成",
      "{C:inactive}（例如：{C:attention}10 8 6 5 3{C:inactive}）"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_hologram",
    "enName": "Hologram",
    "zhName": "全息影像",
    "rarity": 2,
    "order": 70,
    "cost": 7,
    "pos": {
      "x": 4,
      "y": 12
    },
    "image": "Hologram.png",
    "config": {
      "extra": 0.25,
      "Xmult": 1
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每添加一张{C:attention}卡牌{}",
      "到你的牌组中，",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.25,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_vagabond",
    "enName": "Vagabond",
    "zhName": "流浪者",
    "rarity": 3,
    "order": 71,
    "cost": 8,
    "pos": {
      "x": 5,
      "y": 12
    },
    "image": "Vagabond.png",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果在出牌时",
      "资金少于等于{C:money}$#1#{}",
      "则获得一张{C:purple}塔罗牌{}"
    ],
    "vars": [
      4
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_baron",
    "enName": "Baron",
    "zhName": "男爵",
    "rarity": 3,
    "order": 72,
    "cost": 8,
    "pos": {
      "x": 6,
      "y": 12
    },
    "image": "Baron.png",
    "config": {
      "extra": 1.5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "留在手牌中的",
      "每一张{C:attention}K{}",
      "会给予{X:mult,C:white} X#1# {}倍率"
    ],
    "vars": [
      1.5
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_cloud_9",
    "enName": "Cloud 9",
    "zhName": "9霄云外",
    "rarity": 2,
    "order": 73,
    "cost": 7,
    "pos": {
      "x": 7,
      "y": 12
    },
    "image": "Cloud 9.png",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每个回合结束时",
      "你{C:attention}完整牌组{}内的每张{C:attention}9{}",
      "使你获得{C:money}$#1#{}",
      "{C:inactive}(当前{C:money}$#2#{}{C:inactive})"
    ],
    "vars": [
      1,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_rocket",
    "enName": "Rocket",
    "zhName": "火箭",
    "rarity": 2,
    "order": 74,
    "cost": 6,
    "pos": {
      "x": 8,
      "y": 12
    },
    "image": "Rocket.png",
    "config": {
      "extra": {
        "dollars": 1,
        "increase": 2
      }
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每个回合结束时你获得{C:money}$#1#{}",
      "击败{C:attention}Boss盲注{}",
      "会使这一金额增加{C:money}$#2#{}"
    ],
    "vars": [
      1,
      2
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_obelisk",
    "enName": "Obelisk",
    "zhName": "方尖石塔",
    "rarity": 3,
    "order": 75,
    "cost": 8,
    "pos": {
      "x": 9,
      "y": 12
    },
    "image": "Obelisk.png",
    "config": {
      "extra": 0.2,
      "Xmult": 1
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "连续打出不是你",
      "最常用的{C:attention}牌型{}时",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "失败将会重置倍率",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.2,
      1
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_midas_mask",
    "enName": "Midas Mask",
    "zhName": "迈达斯面具",
    "rarity": 2,
    "order": 76,
    "cost": 7,
    "pos": {
      "x": 0,
      "y": 13
    },
    "image": "Midas Mask.png",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的所有{C:attention}人头牌{}",
      "在计分时",
      "变为{C:attention}黄金牌{}"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_luchador",
    "enName": "Luchador",
    "zhName": "摔跤手",
    "rarity": 2,
    "order": 77,
    "cost": 5,
    "pos": {
      "x": 1,
      "y": 13
    },
    "image": "Luchador.png",
    "config": {},
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "售出这张小丑牌",
      "会消除当前回合中",
      "{C:attention}Boss盲注{}的限制条件"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_photograph",
    "enName": "Photograph",
    "zhName": "照片",
    "rarity": 1,
    "order": 78,
    "cost": 5,
    "pos": {
      "x": 2,
      "y": 13
    },
    "image": "Photograph.png",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的第一张{C:attention}人头牌{}",
      "在计分时",
      "会给予{X:mult,C:white} X#1# {}倍率"
    ],
    "vars": [
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_gift",
    "enName": "Gift Card",
    "zhName": "礼品卡",
    "rarity": 2,
    "order": 79,
    "cost": 6,
    "pos": {
      "x": 3,
      "y": 13
    },
    "image": "Gift Card.png",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在每回合结束时",
      "使拥有的每张{C:attention}小丑牌{}",
      "和{C:attention}消耗牌{}",
      "{C:attention}售价{}增加{C:money}$#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_turtle_bean",
    "enName": "Turtle Bean",
    "zhName": "黑龟豆",
    "rarity": 2,
    "order": 80,
    "cost": 6,
    "pos": {
      "x": 4,
      "y": 13
    },
    "image": "Turtle Bean.png",
    "config": {
      "extra": {
        "h_size": 5,
        "h_mod": 1
      }
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "手牌上限{C:attention}+#1#{}",
      "每回合结束时减{C:red}#2#{}"
    ],
    "vars": [
      5,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_erosion",
    "enName": "Erosion",
    "zhName": "侵蚀",
    "rarity": 2,
    "order": 81,
    "cost": 6,
    "pos": {
      "x": 5,
      "y": 13
    },
    "image": "Erosion.png",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在你的牌组中",
      "每比完整的{C:attention}#3#{}张牌少一张",
      "就获得{C:red}+#1#{}倍率",
      "{C:inactive}（当前为{C:red}+#2#{C:inactive}倍率）"
    ],
    "vars": [
      4,
      52,
      52
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_reserved_parking",
    "enName": "Reserved Parking",
    "zhName": "私人车位",
    "rarity": 1,
    "order": 82,
    "cost": 6,
    "pos": {
      "x": 6,
      "y": 13
    },
    "image": "Reserved Parking.png",
    "config": {
      "extra": {
        "odds": 2,
        "dollars": 1
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "留在手牌中的",
      "每一张{C:attention}人头牌{}",
      "有{C:green}#2#/#3#{}几率",
      "给予{C:money}$#1#{}"
    ],
    "vars": [
      1,
      1,
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_mail",
    "enName": "Mail-In Rebate",
    "zhName": "邮件回扣",
    "rarity": 1,
    "order": 83,
    "cost": 4,
    "pos": {
      "x": 7,
      "y": 13
    },
    "image": "Mail-In Rebate.png",
    "config": {
      "extra": 5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每弃掉一张{C:attention}#2#{}",
      "即可获得{C:money}$#1#{}",
      "每个回合点数都会变"
    ],
    "vars": [
      5,
      null
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_to_the_moon",
    "enName": "To the Moon",
    "zhName": "冲向月球",
    "rarity": 2,
    "order": 84,
    "cost": 5,
    "pos": {
      "x": 8,
      "y": 13
    },
    "image": "To the Moon.png",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "回合结束时",
      "每拥有{C:money}$5{}",
      "可以额外获得{C:money}$#1#{}的{C:attention}利息{}"
    ],
    "vars": [
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_hallucination",
    "enName": "Hallucination",
    "zhName": "幻觉",
    "rarity": 1,
    "order": 85,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 13
    },
    "image": "Hallucination.png",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打开任一{C:attention}补充包{}时",
      "有{C:green}#1#/#2#{}几率",
      "生成一张{C:attention}塔罗牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [
      1,
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_fortune_teller",
    "enName": "Fortune Teller",
    "zhName": "占卜师",
    "rarity": 1,
    "order": 86,
    "cost": 6,
    "pos": {
      "x": 7,
      "y": 5
    },
    "image": "Fortune Teller.png",
    "effect": "",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "本赛局内每使用过一张{C:purple}塔罗牌{}",
      "这张小丑获得{C:red}+#1#{}倍率",
      "{C:inactive}（当前为{C:red}+#2#{C:inactive}）"
    ],
    "vars": [
      1,
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_juggler",
    "enName": "Juggler",
    "zhName": "杂耍师",
    "rarity": 1,
    "order": 87,
    "cost": 4,
    "pos": {
      "x": 0,
      "y": 1
    },
    "image": "Juggler.png",
    "effect": "Hand Size",
    "config": {
      "h_size": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "手牌上限{C:attention}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_drunkard",
    "enName": "Drunkard",
    "zhName": "醉汉",
    "rarity": 1,
    "order": 88,
    "cost": 4,
    "pos": {
      "x": 1,
      "y": 1
    },
    "image": "Drunkard.png",
    "effect": "Discard Size",
    "config": {
      "d_size": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每回合",
      "弃牌次数{C:red}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_stone",
    "enName": "Stone Joker",
    "zhName": "石头小丑",
    "rarity": 2,
    "order": 89,
    "cost": 6,
    "pos": {
      "x": 9,
      "y": 0
    },
    "image": "Stone Joker.png",
    "effect": "Stone Card Buff",
    "config": {
      "extra": 25
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:attention}完整牌组{}内每有一张",
      "{C:attention}石头牌",
      "{C:chips}+#1#{}筹码",
      "{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）"
    ],
    "vars": [
      25,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_golden",
    "enName": "Golden Joker",
    "zhName": "黄金小丑",
    "rarity": 1,
    "order": 90,
    "cost": 6,
    "pos": {
      "x": 9,
      "y": 2
    },
    "image": "Golden Joker.png",
    "effect": "Bonus dollars",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在回合结束时",
      "获得{C:money}$#1#{}"
    ],
    "vars": [
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_lucky_cat",
    "enName": "Lucky Cat",
    "zhName": "招财猫",
    "rarity": 2,
    "order": 91,
    "cost": 6,
    "pos": {
      "x": 5,
      "y": 14
    },
    "image": "Lucky Cat.png",
    "config": {
      "Xmult": 1,
      "extra": 0.25
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每次{C:green}成功{}触发",
      "一张{C:attention}幸运牌{}时",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.25,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_baseball",
    "enName": "Baseball Card",
    "zhName": "棒球卡",
    "rarity": 3,
    "order": 92,
    "cost": 8,
    "pos": {
      "x": 6,
      "y": 14
    },
    "image": "Baseball Card.png",
    "config": {
      "extra": 1.5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每张{C:green}罕见{}小丑牌",
      "会给予{X:mult,C:white} X#1# {}倍率"
    ],
    "vars": [
      1.5
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_bull",
    "enName": "Bull",
    "zhName": "斗牛",
    "rarity": 2,
    "order": 93,
    "cost": 6,
    "pos": {
      "x": 7,
      "y": 14
    },
    "image": "Bull.png",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每拥有{C:money}$1{}",
      "{C:chips}+#1#{}筹码",
      "{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）"
    ],
    "vars": [
      2,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_diet_cola",
    "enName": "Diet Cola",
    "zhName": "零糖可乐",
    "rarity": 2,
    "order": 94,
    "cost": 6,
    "pos": {
      "x": 8,
      "y": 14
    },
    "image": "Diet Cola.png",
    "config": {},
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "售出这牌就可以",
      "创建一个免费的",
      "{C:attention}#1#"
    ],
    "vars": [
      null
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_trading",
    "enName": "Trading Card",
    "zhName": "交易卡",
    "rarity": 2,
    "order": 95,
    "cost": 6,
    "pos": {
      "x": 9,
      "y": 14
    },
    "image": "Trading Card.png",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果每回合的{C:attention}第一次弃牌{}",
      "只有{C:attention}1{}张牌，则将其",
      "摧毁并获得{C:money}$#1#"
    ],
    "vars": [
      3
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_flash",
    "enName": "Flash Card",
    "zhName": "闪示卡",
    "rarity": 2,
    "order": 96,
    "cost": 5,
    "pos": {
      "x": 0,
      "y": 15
    },
    "image": "Flash Card.png",
    "config": {
      "extra": 2,
      "mult": 0
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "在商店中每{C:attention}重掷{}一次",
      "这张小丑牌获得{C:mult}+#1#{}倍率",
      "{C:inactive}（当前为{C:mult}+#2#{C:inactive}倍率）"
    ],
    "vars": [
      2,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_popcorn",
    "enName": "Popcorn",
    "zhName": "爆米花",
    "rarity": 1,
    "order": 97,
    "cost": 5,
    "pos": {
      "x": 1,
      "y": 15
    },
    "image": "Popcorn.png",
    "config": {
      "mult": 20,
      "extra": 4
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "{C:mult}+#1#{}倍率",
      "每回合结束时",
      "{C:mult}-#2#{}倍率"
    ],
    "vars": [
      0,
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_trousers",
    "enName": "Spare Trousers",
    "zhName": "备用裤子",
    "rarity": 2,
    "order": 98,
    "cost": 6,
    "pos": {
      "x": 4,
      "y": 15
    },
    "image": "Spare Trousers.png",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "如果打出的牌中包含",
      "{C:attention}#2#",
      "则这张小丑牌获得{C:mult}+#1#{}倍率",
      "{C:inactive}（当前为{C:red}+#3#{C:inactive}倍率）"
    ],
    "vars": [
      2,
      "两对",
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_ancient",
    "enName": "Ancient Joker",
    "zhName": "古老小丑",
    "rarity": 3,
    "order": 99,
    "cost": 8,
    "pos": {
      "x": 7,
      "y": 15
    },
    "image": "Ancient Joker.png",
    "config": {
      "extra": 1.5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{V:1}#2#{}牌",
      "在计分时",
      "会给予{X:mult,C:white} X#1# {}倍率",
      "{s:0.8}回合结束时改变需求花色"
    ],
    "vars": [
      1.5,
      null
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_ramen",
    "enName": "Ramen",
    "zhName": "拉面",
    "rarity": 2,
    "order": 100,
    "cost": 6,
    "pos": {
      "x": 2,
      "y": 15
    },
    "image": "Ramen.png",
    "config": {
      "Xmult": 2,
      "extra": 0.01
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "{X:mult,C:white}X#1#{}倍率",
      "每{C:attention}弃掉一张牌{}",
      "失去{X:mult,C:white}X#2#{}倍率"
    ],
    "vars": [
      1,
      0.01
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_walkie_talkie",
    "enName": "Walkie Talkie",
    "zhName": "对讲机",
    "rarity": 1,
    "order": 101,
    "cost": 4,
    "pos": {
      "x": 8,
      "y": 15
    },
    "image": "Walkie Talkie.png",
    "config": {
      "extra": {
        "chips": 10,
        "mult": 4
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的每张{C:attention}10{}和{C:attention}4",
      "在计分时获得{C:chips}+#1#{}筹码",
      "以及{C:mult}+#2#{}倍率"
    ],
    "vars": [
      10,
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_selzer",
    "enName": "Seltzer",
    "zhName": "苏打水",
    "rarity": 2,
    "order": 102,
    "cost": 6,
    "pos": {
      "x": 3,
      "y": 15
    },
    "image": "Seltzer.png",
    "config": {
      "extra": 10
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "在接下来的{C:attention}#1#{}次出牌中",
      "重新触发所有",
      "打出的卡牌"
    ],
    "vars": [
      10
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_castle",
    "enName": "Castle",
    "zhName": "城堡",
    "rarity": 2,
    "order": 103,
    "cost": 6,
    "pos": {
      "x": 9,
      "y": 15
    },
    "image": "Castle.png",
    "config": {
      "extra": {
        "chips": 0,
        "chip_mod": 3
      }
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每弃掉一张{V:1}#2#{}牌",
      "这张小丑牌获得{C:chips}+#1#{}筹码",
      "每个回合花色都会变",
      "{C:inactive}（当前为{C:chips}+#3#{C:inactive}筹码）"
    ],
    "vars": [
      3,
      null,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_smiley",
    "enName": "Smiley Face",
    "zhName": "微笑表情",
    "rarity": 1,
    "order": 104,
    "cost": 4,
    "pos": {
      "x": 6,
      "y": 15
    },
    "image": "Smiley Face.png",
    "config": {
      "extra": 5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{C:attention}人头牌{}",
      "在计分时",
      "给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      5
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_campfire",
    "enName": "Campfire",
    "zhName": "篝火",
    "rarity": 3,
    "order": 105,
    "cost": 9,
    "pos": {
      "x": 5,
      "y": 15
    },
    "image": "Campfire.png",
    "config": {
      "extra": 0.25
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每{C:attention}售出{}一张牌",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "{C:attention}Boss盲注{}被击败时重置倍率",
      "{C:inactive}（当前为{X:mult,C:white}X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.25,
      1
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_ticket",
    "enName": "Golden Ticket",
    "zhName": "黄金门票",
    "rarity": 1,
    "order": 106,
    "cost": 5,
    "pos": {
      "x": 5,
      "y": 3
    },
    "image": "Golden Ticket.png",
    "effect": "dollars for Gold cards",
    "config": {
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{C:attention}黃金牌{}",
      "在计分时获得{C:money}$#1#{}"
    ],
    "vars": [
      4
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_mr_bones",
    "enName": "Mr. Bones",
    "zhName": "骷髅先生",
    "rarity": 2,
    "order": 107,
    "cost": 5,
    "pos": {
      "x": 3,
      "y": 4
    },
    "image": "Mr. Bones.png",
    "effect": "Prevent Death",
    "config": {},
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "如果最终得到的",
      "筹码至少是",
      "所需筹码的{C:attention}25%",
      "则不会死亡",
      "{S:1.1,C:red,E:2}自毁{}"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_acrobat",
    "enName": "Acrobat",
    "zhName": "杂技演员",
    "rarity": 2,
    "order": 108,
    "cost": 6,
    "pos": {
      "x": 2,
      "y": 1
    },
    "image": "Acrobat.png",
    "effect": "Shop size",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每回合的最后一次",
      "{C:attention}出牌{}时，{X:red,C:white} X#1# {}倍率"
    ],
    "vars": [
      3
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_sock_and_buskin",
    "enName": "Sock and Buskin",
    "zhName": "喜与悲",
    "rarity": 2,
    "order": 109,
    "cost": 6,
    "pos": {
      "x": 3,
      "y": 1
    },
    "image": "Sock and Buskin.png",
    "effect": "Face card double",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "重新触发所有",
      "打出的{C:attention}人头牌{}"
    ],
    "vars": [
      2
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_swashbuckler",
    "enName": "Swashbuckler",
    "zhName": "侠盗",
    "rarity": 1,
    "order": 110,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 5
    },
    "image": "Swashbuckler.png",
    "effect": "Set Mult",
    "config": {
      "mult": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "将拥有的所有其他",
      "{C:attention}小丑牌{}的总售价",
      "添加至倍率",
      "{C:inactive}（当前为{C:mult}+#1#{C:inactive}倍率）"
    ],
    "vars": [
      0
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_troubadour",
    "enName": "Troubadour",
    "zhName": "游吟诗人",
    "rarity": 2,
    "order": 111,
    "cost": 6,
    "pos": {
      "x": 0,
      "y": 2
    },
    "image": "Troubadour.png",
    "effect": "Hand Size, Plays",
    "config": {
      "extra": {
        "h_size": 2,
        "h_plays": -1
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:attention}+#1#{}手牌上限",
      "每回合出牌次数{C:blue}-#2#{}"
    ],
    "vars": [
      2,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_certificate",
    "enName": "Certificate",
    "zhName": "证书",
    "rarity": 2,
    "order": 112,
    "cost": 6,
    "pos": {
      "x": 8,
      "y": 8
    },
    "image": "Certificate.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "回合开始时",
      "随机添加一张",
      "带随机{C:attention}蜡封{}的{C:attention}牌",
      "到手牌中"
    ],
    "vars": [
      null
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_smeared",
    "enName": "Smeared Joker",
    "zhName": "模糊小丑",
    "rarity": 2,
    "order": 113,
    "cost": 7,
    "pos": {
      "x": 4,
      "y": 6
    },
    "image": "Smeared Joker.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:hearts}红桃{}和{C:diamonds}方片",
      "视作同一花色，",
      "{C:spades}黑桃{}和{C:clubs}梅花",
      "也视作同一花色"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_throwback",
    "enName": "Throwback",
    "zhName": "回溯",
    "rarity": 2,
    "order": 114,
    "cost": 6,
    "pos": {
      "x": 5,
      "y": 7
    },
    "image": "Throwback.png",
    "effect": "",
    "config": {
      "extra": 0.25
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "本赛局内每跳过一次",
      "{C:attention}盲注{}，获得{X:mult,C:white}X#1#{}倍率",
      "{C:inactive}（当前为{X:mult,C:white} X#2# {C:inactive}倍率）"
    ],
    "vars": [
      0.25,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_hanging_chad",
    "enName": "Hanging Chad",
    "zhName": "未断选票",
    "rarity": 1,
    "order": 115,
    "cost": 4,
    "pos": {
      "x": 9,
      "y": 6
    },
    "image": "Hanging Chad.png",
    "effect": "",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的牌中",
      "{C:attention}第一张{}计分牌",
      "额外触发{C:attention}#1#{}次"
    ],
    "vars": [
      2
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_rough_gem",
    "enName": "Rough Gem",
    "zhName": "璞玉",
    "rarity": 2,
    "order": 116,
    "cost": 7,
    "pos": {
      "x": 9,
      "y": 7
    },
    "image": "Rough Gem.png",
    "effect": "",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:diamonds}方块{}花色牌",
      "在计分时给予{C:money}$#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_bloodstone",
    "enName": "Bloodstone",
    "zhName": "血石",
    "rarity": 2,
    "order": 117,
    "cost": 7,
    "pos": {
      "x": 0,
      "y": 8
    },
    "image": "Bloodstone.png",
    "effect": "",
    "config": {
      "extra": {
        "odds": 2,
        "Xmult": 1.5
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:hearts}红桃{}花色牌",
      "在计分时有{c:green}#1#/#2#{}几率",
      "给予{X:mult,C:white}X#3#{}倍率"
    ],
    "vars": [
      1,
      2,
      1.5
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_arrowhead",
    "enName": "Arrowhead",
    "zhName": "箭头",
    "rarity": 2,
    "order": 118,
    "cost": 7,
    "pos": {
      "x": 1,
      "y": 8
    },
    "image": "Arrowhead.png",
    "effect": "",
    "config": {
      "extra": 50
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:spades}黑桃{}花色牌",
      "在计分时给予{C:chips}+#1#{}筹码"
    ],
    "vars": [
      50
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_onyx_agate",
    "enName": "Onyx Agate",
    "zhName": "缟玛瑙",
    "rarity": 2,
    "order": 119,
    "cost": 7,
    "pos": {
      "x": 2,
      "y": 8
    },
    "image": "Onyx Agate.png",
    "effect": "",
    "config": {
      "extra": 7
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的",
      "{C:clubs}梅花{}花色牌",
      "在计分时给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      7
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_glass",
    "enName": "Glass Joker",
    "zhName": "玻璃小丑",
    "rarity": 2,
    "order": 120,
    "cost": 6,
    "pos": {
      "x": 1,
      "y": 3
    },
    "image": "Glass Joker.png",
    "effect": "Glass Card",
    "config": {
      "extra": 0.75,
      "Xmult": 1
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每摧毁一张",
      "{C:attention}玻璃牌",
      "这张小丑获得{X:mult,C:white}X#1#{}倍率",
      "{C:inactive}（当前为{X:mult,C:white} X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.75,
      1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_ring_master",
    "enName": "Showman",
    "zhName": "马戏团长",
    "rarity": 2,
    "order": 121,
    "cost": 5,
    "pos": {
      "x": 6,
      "y": 5
    },
    "image": "Showman.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:attention}小丑牌{}、{C:tarot}塔罗牌{}、{C:planet}星球牌{}",
      "和{C:planet}幻灵牌{}可以同时",
      "出现复数张"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_flower_pot",
    "enName": "Flower Pot",
    "zhName": "花盆",
    "rarity": 2,
    "order": 122,
    "cost": 6,
    "pos": {
      "x": 0,
      "y": 6
    },
    "image": "Flower Pot.png",
    "effect": "",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌型中，包含",
      "{C:diamonds}方片{}、{C:clubs}梅花{}、",
      "{C:hearts}红桃{}、{C:spades}黑桃{}牌各一张，",
      "则{X:mult,C:white} X#1# {}倍率"
    ],
    "vars": [
      3
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_blueprint",
    "enName": "Blueprint",
    "zhName": "蓝图",
    "rarity": 3,
    "order": 123,
    "cost": 10,
    "pos": {
      "x": 0,
      "y": 3
    },
    "image": "Blueprint.png",
    "effect": "Copycat",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "复制",
      "右侧{C:attention}小丑牌{}的能力"
    ],
    "vars": [],
    "colour": "#fe5f55"
  },
  {
    "key": "j_wee",
    "enName": "Wee Joker",
    "zhName": "小小丑",
    "rarity": 3,
    "order": 124,
    "cost": 8,
    "pos": {
      "x": 0,
      "y": 0
    },
    "image": "Wee Joker.png",
    "effect": "",
    "config": {
      "extra": {
        "chips": 0,
        "chip_mod": 8
      }
    },
    "eternal_compat": true,
    "perishable_compat": false,
    "text": [
      "每有一张打出的{C:attention}2{}计分时",
      "这张小丑牌获得",
      "{C:chips}+#2#{}筹码",
      "{C:inactive}（当前为{C:chips}+#1#{C:inactive}筹码）"
    ],
    "vars": [
      0,
      8
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_merry_andy",
    "enName": "Merry Andy",
    "zhName": "快乐安迪",
    "rarity": 2,
    "order": 125,
    "cost": 7,
    "pos": {
      "x": 8,
      "y": 0
    },
    "image": "Merry Andy.png",
    "effect": "",
    "config": {
      "d_size": 3,
      "h_size": -1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每回合",
      "弃牌次数{C:red}+#1#{}",
      "手牌上限{C:red}#2#{}"
    ],
    "vars": [
      3,
      -1
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_oops",
    "enName": "Oops! All 6s",
    "zhName": "六六大顺",
    "rarity": 2,
    "order": 126,
    "cost": 4,
    "pos": {
      "x": 5,
      "y": 6
    },
    "image": "Oops! All 6s.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "将所有以{C:attention}数字标注{}出的",
      "{C:green,E:1,S:1.1}几率{}翻倍",
      "{C:inactive}（例如：{C:green}1/3{C:inactive}几率 -> {C:green}2/3{C:inactive}几率）"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_idol",
    "enName": "The Idol",
    "zhName": "偶像",
    "rarity": 2,
    "order": 127,
    "cost": 6,
    "pos": {
      "x": 6,
      "y": 7
    },
    "image": "The Idol.png",
    "effect": "",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每张打出的{V:1}#3#{}{C:attention}#2#",
      "在计分时",
      "给予{X:mult,C:white} X#1# {}倍率",
      "{s:0.8}每回合卡牌都会变动"
    ],
    "vars": [
      2,
      null,
      null
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_seeing_double",
    "enName": "Seeing Double",
    "zhName": "重影",
    "rarity": 2,
    "order": 128,
    "cost": 6,
    "pos": {
      "x": 4,
      "y": 4
    },
    "image": "Seeing Double.png",
    "effect": "X1.5 Mult club 7",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中，包含",
      "一张计分的{C:clubs}梅花{}牌和",
      "一张计分的任何其他{C:attention}花色{}牌",
      "则{X:mult,C:white} X#1# {}倍率"
    ],
    "vars": [
      2
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_matador",
    "enName": "Matador",
    "zhName": "斗牛士",
    "rarity": 2,
    "order": 129,
    "cost": 7,
    "pos": {
      "x": 4,
      "y": 5
    },
    "image": "Matador.png",
    "effect": "",
    "config": {
      "extra": 8
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果出牌触发了",
      "{C:attention}Boss盲注{}的限制条件",
      "获得{C:money}$#1#{}"
    ],
    "vars": [
      8
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_hit_the_road",
    "enName": "Hit the Road",
    "zhName": "上路吧杰克",
    "rarity": 3,
    "order": 130,
    "cost": 8,
    "pos": {
      "x": 8,
      "y": 5
    },
    "image": "Hit the Road.png",
    "effect": "Jack Discard Effect",
    "config": {
      "extra": 0.5
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "本回合中，每弃掉一张",
      "{C:attention}J{}牌",
      "这张小丑牌获得{X:mult,C:white}X#1# {}倍率",
      "{C:inactive}（当前为{X:mult,C:white} X#2#{C:inactive}倍率）"
    ],
    "vars": [
      0.5,
      1
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_duo",
    "enName": "The Duo",
    "zhName": "二重奏",
    "rarity": 3,
    "order": 131,
    "cost": 8,
    "pos": {
      "x": 5,
      "y": 4
    },
    "image": "The Duo.png",
    "effect": "X1.5 Mult",
    "config": {
      "Xmult": 2,
      "type": "Pair"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      1,
      "对子"
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_trio",
    "enName": "The Trio",
    "zhName": "三重奏",
    "rarity": 3,
    "order": 132,
    "cost": 8,
    "pos": {
      "x": 6,
      "y": 4
    },
    "image": "The Trio.png",
    "effect": "X2 Mult",
    "config": {
      "Xmult": 3,
      "type": "Three of a Kind"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      1,
      "三条"
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_family",
    "enName": "The Family",
    "zhName": "一家人",
    "rarity": 3,
    "order": 133,
    "cost": 8,
    "pos": {
      "x": 7,
      "y": 4
    },
    "image": "The Family.png",
    "effect": "X3 Mult",
    "config": {
      "Xmult": 4,
      "type": "Four of a Kind"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      1,
      "四条"
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_order",
    "enName": "The Order",
    "zhName": "秩序",
    "rarity": 3,
    "order": 134,
    "cost": 8,
    "pos": {
      "x": 8,
      "y": 4
    },
    "image": "The Order.png",
    "effect": "X3 Mult",
    "config": {
      "Xmult": 3,
      "type": "Straight"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      1,
      "顺子"
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_tribe",
    "enName": "The Tribe",
    "zhName": "部落",
    "rarity": 3,
    "order": 135,
    "cost": 8,
    "pos": {
      "x": 9,
      "y": 4
    },
    "image": "The Tribe.png",
    "effect": "X3 Mult",
    "config": {
      "Xmult": 2,
      "type": "Flush"
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果打出的牌中",
      "包含{C:attention}#2#",
      "{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      1,
      "同花"
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_stuntman",
    "enName": "Stuntman",
    "zhName": "特技演员",
    "rarity": 3,
    "order": 136,
    "cost": 7,
    "pos": {
      "x": 8,
      "y": 6
    },
    "image": "Stuntman.png",
    "effect": "",
    "config": {
      "extra": {
        "h_size": 2,
        "chip_mod": 250
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "{C:chips}+#1#{}筹码",
      "手牌上限{C:attention}-#2#{}"
    ],
    "vars": [
      250,
      2
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_invisible",
    "enName": "Invisible Joker",
    "zhName": "隐形小丑",
    "rarity": 3,
    "order": 137,
    "cost": 8,
    "pos": {
      "x": 1,
      "y": 7
    },
    "image": "Invisible Joker.png",
    "effect": "",
    "config": {
      "extra": 2
    },
    "eternal_compat": false,
    "perishable_compat": true,
    "text": [
      "经过{C:attention}#1#{}个回合后",
      "售出此卡牌可以",
      "随机{C:attention}复制{}一张小丑牌",
      "{C:inactive}(当前为{C:attention}#2#{C:inactive}/#1#)"
    ],
    "vars": [
      2,
      0
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_brainstorm",
    "enName": "Brainstorm",
    "zhName": "头脑风暴",
    "rarity": 3,
    "order": 138,
    "cost": 10,
    "pos": {
      "x": 7,
      "y": 7
    },
    "image": "Brainstorm.png",
    "effect": "Copycat",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "复制最左边的",
      "{C:attention}小丑牌的能力"
    ],
    "vars": [],
    "colour": "#fe5f55"
  },
  {
    "key": "j_satellite",
    "enName": "Satellite",
    "zhName": "卫星",
    "rarity": 2,
    "order": 139,
    "cost": 6,
    "pos": {
      "x": 8,
      "y": 7
    },
    "image": "Satellite.png",
    "effect": "",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "本赛局每使用过一种",
      "{C:planet}星球牌{}，每回合结束时",
      "可得到{C:money}$#1#{}",
      "{C:inactive}（当前{C:money}$#2#{C:inactive}）"
    ],
    "vars": [
      1,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_shoot_the_moon",
    "enName": "Shoot the Moon",
    "zhName": "射月",
    "rarity": 1,
    "order": 140,
    "cost": 5,
    "pos": {
      "x": 2,
      "y": 6
    },
    "image": "Shoot the Moon.png",
    "effect": "",
    "config": {
      "extra": 13
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "留在手牌中的",
      "每一张{C:attention}Q",
      "给予{C:mult}+#1#{}倍率"
    ],
    "vars": [
      13
    ],
    "colour": "#009dff"
  },
  {
    "key": "j_drivers_license",
    "enName": "Driver's License",
    "zhName": "驾驶执照",
    "rarity": 3,
    "order": 141,
    "cost": 7,
    "pos": {
      "x": 0,
      "y": 7
    },
    "image": "Driver.png",
    "effect": "",
    "config": {
      "extra": 3
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "如果牌组中至少有",
      "{C:attention}16张增强卡牌，",
      "则{X:mult,C:white} X#1# {}倍率",
      "{C:inactive}（当前{C:attention}#2#{C:inactive}）"
    ],
    "vars": [
      3,
      null
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_cartomancer",
    "enName": "Cartomancer",
    "zhName": "卡牌术士",
    "rarity": 2,
    "order": 142,
    "cost": 6,
    "pos": {
      "x": 7,
      "y": 3
    },
    "image": "Cartomancer.png",
    "effect": "Tarot Buff",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在选择{C:attention}盲注{}时",
      "生成一张{C:tarot}塔罗牌{}",
      "{C:inactive}（必须有空位）"
    ],
    "vars": [],
    "colour": "#4bc292"
  },
  {
    "key": "j_astronomer",
    "enName": "Astronomer",
    "zhName": "天文学家",
    "rarity": 2,
    "order": 143,
    "cost": 8,
    "pos": {
      "x": 2,
      "y": 7
    },
    "image": "Astronomer.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "所有{C:planet}星球牌{}",
      "和{C:planet}天体补充包{}",
      "在商店内都{C:attention}免费"
    ],
    "vars": [
      null
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_burnt",
    "enName": "Burnt Joker",
    "zhName": "烧焦小丑",
    "rarity": 3,
    "order": 144,
    "cost": 8,
    "pos": {
      "x": 3,
      "y": 7
    },
    "image": "Burnt Joker.png",
    "effect": "",
    "config": {
      "h_size": 0,
      "extra": 4
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "升级每回合",
      "第一次{C:attention}被弃掉的",
      "牌型的等级"
    ],
    "vars": [
      0,
      4
    ],
    "colour": "#fe5f55"
  },
  {
    "key": "j_bootstraps",
    "enName": "Bootstraps",
    "zhName": "提靴带",
    "rarity": 2,
    "order": 145,
    "cost": 7,
    "pos": {
      "x": 9,
      "y": 8
    },
    "image": "Bootstraps.png",
    "effect": "",
    "config": {
      "extra": {
        "mult": 2,
        "dollars": 5
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每拥有{C:money}$#2#{}",
      "{C:mult}+#1#{}倍率",
      "{C:inactive}（当前为{C:mult}+#3#{C:inactive}倍率）"
    ],
    "vars": [
      2,
      5,
      0
    ],
    "colour": "#4bc292"
  },
  {
    "key": "j_caino",
    "enName": "Caino",
    "zhName": "卡尼奥",
    "rarity": 4,
    "order": 146,
    "cost": 20,
    "pos": {
      "x": 3,
      "y": 8
    },
    "image": "Caino.png",
    "effect": "",
    "config": {
      "extra": 1
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每当一张{C:attention}人头牌{}",
      "被摧毁时",
      "这张小丑牌获得{X:mult,C:white}X#1#{}倍率",
      "{C:inactive}（当前为{X:mult,C:white} X#2#{C:inactive}倍率）"
    ],
    "vars": [
      1,
      0
    ],
    "colour": "#b26cbb"
  },
  {
    "key": "j_triboulet",
    "enName": "Triboulet",
    "zhName": "特里布莱",
    "rarity": 4,
    "order": 147,
    "cost": 20,
    "pos": {
      "x": 4,
      "y": 8
    },
    "image": "Triboulet.png",
    "effect": "",
    "config": {
      "extra": 2
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "打出的{C:attention}K{}和{C:attention}Q",
      "在计分时",
      "给予{X:mult,C:white}X#1#{}倍率"
    ],
    "vars": [
      2
    ],
    "colour": "#b26cbb"
  },
  {
    "key": "j_yorick",
    "enName": "Yorick",
    "zhName": "约里克",
    "rarity": 4,
    "order": 148,
    "cost": 20,
    "pos": {
      "x": 5,
      "y": 8
    },
    "image": "Yorick.png",
    "effect": "",
    "config": {
      "extra": {
        "xmult": 1,
        "discards": 23
      }
    },
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "每弃掉{C:attention}#2#{C:inactive}[#3#]{}张牌",
      "这张小丑牌获得{X:mult,C:white} X#1# {}倍率",
      "{C:inactive}（当前为{X:mult,C:white} X#4# {C:inactive}倍率）"
    ],
    "vars": [
      1,
      23,
      0,
      1
    ],
    "colour": "#b26cbb"
  },
  {
    "key": "j_chicot",
    "enName": "Chicot",
    "zhName": "希科",
    "rarity": 4,
    "order": 149,
    "cost": 20,
    "pos": {
      "x": 6,
      "y": 8
    },
    "image": "Chicot.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "所有{C:attention}Boss盲注",
      "限制条件消失"
    ],
    "vars": [],
    "colour": "#b26cbb"
  },
  {
    "key": "j_perkeo",
    "enName": "Perkeo",
    "zhName": "帕奇欧",
    "rarity": 4,
    "order": 150,
    "cost": 20,
    "pos": {
      "x": 7,
      "y": 8
    },
    "image": "Perkeo.png",
    "effect": "",
    "config": {},
    "eternal_compat": true,
    "perishable_compat": true,
    "text": [
      "在离开商店时",
      "随机复制{C:attention}1{}张",
      "拥有的{C:attention}消耗牌{}",
      "并给那张牌{C:dark_edition}负片{}效果"
    ],
    "vars": [
      null
    ],
    "colour": "#b26cbb"
  }
];
