// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: Code/game.lua P_BLINDS / P_TAGS / P_CENTERS(v_*)（新开局预掷的三个随机池）
export interface BossPoolDef {
  key: string;
  /** 出现的最低底注（boss.min） */
  min: number;
  /** 终局 Boss（第 8 底注才有资格出现，showdown = true） */
  showdown: boolean;
}

export const BOSS_POOL: BossPoolDef[] = [
  {
    "key": "bl_arm",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_club",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_eye",
    "min": 3,
    "showdown": false
  },
  {
    "key": "bl_final_acorn",
    "min": 10,
    "showdown": true
  },
  {
    "key": "bl_final_bell",
    "min": 10,
    "showdown": true
  },
  {
    "key": "bl_final_heart",
    "min": 10,
    "showdown": true
  },
  {
    "key": "bl_final_leaf",
    "min": 10,
    "showdown": true
  },
  {
    "key": "bl_final_vessel",
    "min": 10,
    "showdown": true
  },
  {
    "key": "bl_fish",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_flint",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_goad",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_head",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_hook",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_manacle",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_mark",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_mouth",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_needle",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_ox",
    "min": 6,
    "showdown": false
  },
  {
    "key": "bl_pillar",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_plant",
    "min": 4,
    "showdown": false
  },
  {
    "key": "bl_psychic",
    "min": 1,
    "showdown": false
  },
  {
    "key": "bl_serpent",
    "min": 5,
    "showdown": false
  },
  {
    "key": "bl_tooth",
    "min": 3,
    "showdown": false
  },
  {
    "key": "bl_wall",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_water",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_wheel",
    "min": 2,
    "showdown": false
  },
  {
    "key": "bl_window",
    "min": 1,
    "showdown": false
  }
];

export interface TagPoolDef {
  key: string;
  order: number;
  /** 需要该中心已发现才进池（e_polychrome 等）；存档不含图鉴发现状态，掷点按已发现处理 */
  requires: string | null;
  /** 出现的最低底注（min_ante） */
  minAnte: number | null;
}

export const TAG_POOL: TagPoolDef[] = [
  {
    "key": "tag_uncommon",
    "order": 1,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_rare",
    "order": 2,
    "requires": "j_blueprint",
    "minAnte": null
  },
  {
    "key": "tag_negative",
    "order": 3,
    "requires": "e_negative",
    "minAnte": 2
  },
  {
    "key": "tag_foil",
    "order": 4,
    "requires": "e_foil",
    "minAnte": null
  },
  {
    "key": "tag_holo",
    "order": 5,
    "requires": "e_holo",
    "minAnte": null
  },
  {
    "key": "tag_polychrome",
    "order": 6,
    "requires": "e_polychrome",
    "minAnte": null
  },
  {
    "key": "tag_investment",
    "order": 7,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_voucher",
    "order": 8,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_boss",
    "order": 9,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_standard",
    "order": 10,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_charm",
    "order": 11,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_meteor",
    "order": 12,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_buffoon",
    "order": 13,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_handy",
    "order": 14,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_garbage",
    "order": 15,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_ethereal",
    "order": 16,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_coupon",
    "order": 17,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_double",
    "order": 18,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_juggle",
    "order": 19,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_d_six",
    "order": 20,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_top_up",
    "order": 21,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_skip",
    "order": 22,
    "requires": null,
    "minAnte": null
  },
  {
    "key": "tag_orbital",
    "order": 23,
    "requires": null,
    "minAnte": 2
  },
  {
    "key": "tag_economy",
    "order": 24,
    "requires": null,
    "minAnte": null
  }
];

export interface VoucherPoolDef {
  key: string;
  order: number;
  /** 升级对：依赖的基础券（used_vouchers 未拥有时本券在池中为 UNAVAILABLE 占位） */
  requires: string[];
  /** 静态解锁标记（false = 需档案解锁；plus 券开局恒因 requires 未满足而占位） */
  unlocked: boolean;
}

export const VOUCHER_POOL: VoucherPoolDef[] = [
  {
    "key": "v_overstock_norm",
    "order": 1,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_overstock_plus",
    "order": 2,
    "requires": [
      "v_overstock_norm"
    ],
    "unlocked": false
  },
  {
    "key": "v_clearance_sale",
    "order": 3,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_liquidation",
    "order": 4,
    "requires": [
      "v_clearance_sale"
    ],
    "unlocked": false
  },
  {
    "key": "v_hone",
    "order": 5,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_glow_up",
    "order": 6,
    "requires": [
      "v_hone"
    ],
    "unlocked": false
  },
  {
    "key": "v_reroll_surplus",
    "order": 7,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_reroll_glut",
    "order": 8,
    "requires": [
      "v_reroll_surplus"
    ],
    "unlocked": false
  },
  {
    "key": "v_crystal_ball",
    "order": 9,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_omen_globe",
    "order": 10,
    "requires": [
      "v_crystal_ball"
    ],
    "unlocked": false
  },
  {
    "key": "v_telescope",
    "order": 11,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_observatory",
    "order": 12,
    "requires": [
      "v_telescope"
    ],
    "unlocked": false
  },
  {
    "key": "v_grabber",
    "order": 13,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_nacho_tong",
    "order": 14,
    "requires": [
      "v_grabber"
    ],
    "unlocked": false
  },
  {
    "key": "v_wasteful",
    "order": 15,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_recyclomancy",
    "order": 16,
    "requires": [
      "v_wasteful"
    ],
    "unlocked": false
  },
  {
    "key": "v_tarot_merchant",
    "order": 17,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_tarot_tycoon",
    "order": 18,
    "requires": [
      "v_tarot_merchant"
    ],
    "unlocked": false
  },
  {
    "key": "v_planet_merchant",
    "order": 19,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_planet_tycoon",
    "order": 20,
    "requires": [
      "v_planet_merchant"
    ],
    "unlocked": false
  },
  {
    "key": "v_seed_money",
    "order": 21,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_money_tree",
    "order": 22,
    "requires": [
      "v_seed_money"
    ],
    "unlocked": false
  },
  {
    "key": "v_blank",
    "order": 23,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_antimatter",
    "order": 24,
    "requires": [
      "v_blank"
    ],
    "unlocked": false
  },
  {
    "key": "v_magic_trick",
    "order": 25,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_illusion",
    "order": 26,
    "requires": [
      "v_magic_trick"
    ],
    "unlocked": false
  },
  {
    "key": "v_hieroglyph",
    "order": 27,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_petroglyph",
    "order": 28,
    "requires": [
      "v_hieroglyph"
    ],
    "unlocked": false
  },
  {
    "key": "v_directors_cut",
    "order": 29,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_retcon",
    "order": 30,
    "requires": [
      "v_directors_cut"
    ],
    "unlocked": false
  },
  {
    "key": "v_paint_brush",
    "order": 31,
    "requires": [],
    "unlocked": true
  },
  {
    "key": "v_palette",
    "order": 32,
    "requires": [
      "v_paint_brush"
    ],
    "unlocked": false
  }
];
