// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: game.lua P_CENTER_POOLS.Stake + Code/localization/zh_CN.lua
export interface StakeDef {
  level: number;
  key: string;
  zhName: string;
  chipFile: string;
  text: string[];
}

export const STAKES: StakeDef[] = [
  {
    "level": 1,
    "key": "stake_white",
    "zhName": "白注",
    "chipFile": "White Chip.png",
    "text": [
      "基础难度"
    ]
  },
  {
    "level": 2,
    "key": "stake_red",
    "zhName": "红注",
    "chipFile": "Red Chip.png",
    "text": [
      "{C:attention}小盲注{}",
      "没有奖励金",
      "{s:0.8}之前所有赌注也都起效"
    ]
  },
  {
    "level": 3,
    "key": "stake_green",
    "zhName": "绿注",
    "chipFile": "Green Chip.png",
    "text": [
      "{C:attention}底注{}提升时",
      "过关需求分数的增速更快",
      "{s:0.8}之前所有赌注也都起效"
    ]
  },
  {
    "level": 4,
    "key": "stake_black",
    "zhName": "黑注",
    "chipFile": "Black Chip.png",
    "text": [
      "商店可能会出现{C:attention}永恒{}小丑牌",
      "{C:inactive,s:0.8}(无法卖出或摧毁)",
      "{s:0.8}之前所有赌注也都起效"
    ]
  },
  {
    "level": 5,
    "key": "stake_blue",
    "zhName": "蓝注",
    "chipFile": "Blue Chip.png",
    "text": [
      "弃牌次数{C:red}-1{}",
      "{s:0.8}之前所有赌注也都起效"
    ]
  },
  {
    "level": 6,
    "key": "stake_purple",
    "zhName": "紫注",
    "chipFile": "Purple Chip.png",
    "text": [
      "{C:attention}底注{}提升时",
      "过关需求分数的增速更快",
      "{s:0.8}之前所有赌注也都起效"
    ]
  },
  {
    "level": 7,
    "key": "stake_orange",
    "zhName": "橙注",
    "chipFile": "Orange Chip.png",
    "text": [
      "商店可能会出现{C:attention}易腐{}小丑牌",
      "{C:inactive,s:0.8}（经过5回合后被削弱）",
      "{s:0.8}之前所有赌注也都起效"
    ]
  },
  {
    "level": 8,
    "key": "stake_gold",
    "zhName": "金注",
    "chipFile": "Gold Chip.png",
    "text": [
      "商店可能会出现{C:attention}租用{}小丑牌",
      "{C:inactive,s:0.8}（售价为$1，每回合花费{C:money,s:0.8}$3{C:inactive,s:0.8}）",
      "{s:0.8}之前所有赌注也都起效"
    ]
  }
];
