// AUTO-GENERATED by scripts/extractData.mjs — DO NOT EDIT
// 来源: Code/game.lua P_CENTERS(v_*) + Code/localization/zh_CN.lua（神形符/岩穴符不收录：ante 回退券，见脚本第 9 节注释）
export interface VoucherDef {
  key: string;
  /** 英文名 = 素材文件名前缀（assets/voucher/<enName>.png） */
  enName: string;
  zhName: string;
  order: number;
  /** 售价（统一 10；开局持有的 used_vouchers 不涉及购买） */
  cost: number;
  /** Vouchers.png 图集坐标 */
  pos: { x: number; y: number };
  /** 素材文件名（保留原始空格） */
  image: string;
  /** 升级对：plus 券依赖的基础券 key（游戏里 plus 只在基础券兑现后上架） */
  requires: string[];
  /** 中心 config，券效果数值来源（Card.apply_to_run 按 name 分支读取 extra） */
  config: Record<string, unknown>;
  /** 中文描述行（原始文本，含 {C:xx} 标记与 #N# 占位符） */
  text: string[];
  /** #N# 取值（= config.extra） */
  vars: (number | string | null)[];
  /** 分类色（G.C.VOUCHER） */
  colour: string;
}

export const VOUCHERS: VoucherDef[] = [
  {
    "key": "v_overstock_norm",
    "enName": "Overstock",
    "zhName": "库存过剩",
    "order": 1,
    "cost": 10,
    "pos": {
      "x": 0,
      "y": 0
    },
    "image": "Overstock.png",
    "requires": [],
    "config": {},
    "text": [
      "商店內",
      "卡牌槽位{C:attention}+1{}"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_overstock_plus",
    "enName": "Overstock Plus",
    "zhName": "库存过剩加强版",
    "order": 2,
    "cost": 10,
    "pos": {
      "x": 0,
      "y": 1
    },
    "image": "Overstock Plus.png",
    "requires": [
      "v_overstock_norm"
    ],
    "config": {},
    "text": [
      "商店内",
      "卡牌槽位{C:attention}+1{}"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_clearance_sale",
    "enName": "Clearance Sale",
    "zhName": "清仓特卖",
    "order": 3,
    "cost": 10,
    "pos": {
      "x": 3,
      "y": 0
    },
    "image": "Clearance Sale.png",
    "requires": [],
    "config": {
      "extra": 25
    },
    "text": [
      "所有卡牌、补充包和优惠券",
      "在店内均可享受{C:attention}#1#%{}折扣"
    ],
    "vars": [
      25
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_liquidation",
    "enName": "Liquidation",
    "zhName": "清算",
    "order": 4,
    "cost": 10,
    "pos": {
      "x": 3,
      "y": 1
    },
    "image": "Liquidation.png",
    "requires": [
      "v_clearance_sale"
    ],
    "config": {
      "extra": 50
    },
    "text": [
      "所有卡牌、补充包和优惠券",
      "在店内均可享受{C:attention}#1#%{}折扣"
    ],
    "vars": [
      50
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_hone",
    "enName": "Hone",
    "zhName": "打磨",
    "order": 5,
    "cost": 10,
    "pos": {
      "x": 4,
      "y": 0
    },
    "image": "Hone.png",
    "requires": [],
    "config": {
      "extra": 2
    },
    "text": [
      "{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}和",
      "{C:dark_edition}多彩卡{}",
      "出现频率{C:attention}X#1#{}"
    ],
    "vars": [
      2
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_glow_up",
    "enName": "Glow Up",
    "zhName": "焕彩",
    "order": 6,
    "cost": 10,
    "pos": {
      "x": 4,
      "y": 1
    },
    "image": "Glow Up.png",
    "requires": [
      "v_hone"
    ],
    "config": {
      "extra": 4
    },
    "text": [
      "{C:dark_edition}闪箔卡{}、{C:dark_edition}镭射卡{}和",
      "{C:dark_edition}多彩卡{}",
      "出现频率{C:attention}X#1#{}"
    ],
    "vars": [
      4
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_reroll_surplus",
    "enName": "Reroll Surplus",
    "zhName": "多次重掷",
    "order": 7,
    "cost": 10,
    "pos": {
      "x": 0,
      "y": 2
    },
    "image": "Reroll Surplus.png",
    "requires": [],
    "config": {
      "extra": 2
    },
    "text": [
      "重掷费用",
      "减少{C:money}$#1#{}"
    ],
    "vars": [
      2
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_reroll_glut",
    "enName": "Reroll Glut",
    "zhName": "重掷加強版",
    "order": 8,
    "cost": 10,
    "pos": {
      "x": 0,
      "y": 3
    },
    "image": "Reroll Glut.png",
    "requires": [
      "v_reroll_surplus"
    ],
    "config": {
      "extra": 2
    },
    "text": [
      "重掷费用",
      "减少{C:money}$#1#{}"
    ],
    "vars": [
      2
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_crystal_ball",
    "enName": "Crystal Ball",
    "zhName": "水晶球",
    "order": 9,
    "cost": 10,
    "pos": {
      "x": 2,
      "y": 2
    },
    "image": "Crystal Ball.png",
    "requires": [],
    "config": {
      "extra": 3
    },
    "text": [
      "消耗牌槽位{C:attention}+1{}"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_omen_globe",
    "enName": "Omen Globe",
    "zhName": "预兆球",
    "order": 10,
    "cost": 10,
    "pos": {
      "x": 2,
      "y": 3
    },
    "image": "Omen Globe.png",
    "requires": [
      "v_crystal_ball"
    ],
    "config": {
      "extra": 4
    },
    "text": [
      "{C:spectral}幻灵牌{}可能",
      "会在任何",
      "{C:attention}秘术包中出现"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_telescope",
    "enName": "Telescope",
    "zhName": "望远镜",
    "order": 11,
    "cost": 10,
    "pos": {
      "x": 3,
      "y": 2
    },
    "image": "Telescope.png",
    "requires": [],
    "config": {
      "extra": 3
    },
    "text": [
      "{C:attention}天体包中的",
      "{C:planet}星球牌{}{}始终有",
      "你最常用的",
      "的{C:attention}牌型"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_observatory",
    "enName": "Observatory",
    "zhName": "天文台",
    "order": 12,
    "cost": 10,
    "pos": {
      "x": 3,
      "y": 3
    },
    "image": "Observatory.png",
    "requires": [
      "v_telescope"
    ],
    "config": {
      "extra": 1.5
    },
    "text": [
      "在您{C:attention}消耗牌栏位{}中",
      "的{C:planet}星球牌{}",
      "会使这一特定{C:attention}牌型",
      "给予{X:red,C:white}X#1#{}倍率"
    ],
    "vars": [
      1.5
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_grabber",
    "enName": "Grabber",
    "zhName": "抓手",
    "order": 13,
    "cost": 10,
    "pos": {
      "x": 5,
      "y": 0
    },
    "image": "Grabber.png",
    "requires": [],
    "config": {
      "extra": 1
    },
    "text": [
      "每回合",
      "出牌次数",
      "永久{C:blue}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_nacho_tong",
    "enName": "Nacho Tong",
    "zhName": "玉米片夹",
    "order": 14,
    "cost": 10,
    "pos": {
      "x": 5,
      "y": 1
    },
    "image": "Nacho Tong.png",
    "requires": [
      "v_grabber"
    ],
    "config": {
      "extra": 1
    },
    "text": [
      "每回合",
      "出牌次数",
      "永久{C:blue}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_wasteful",
    "enName": "Wasteful",
    "zhName": "常弃常新",
    "order": 15,
    "cost": 10,
    "pos": {
      "x": 6,
      "y": 0
    },
    "image": "Wasteful.png",
    "requires": [],
    "config": {
      "extra": 1
    },
    "text": [
      "每回合",
      "弃牌次数",
      "永久{C:blue}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_recyclomancy",
    "enName": "Recyclomancy",
    "zhName": "回收魔法",
    "order": 16,
    "cost": 10,
    "pos": {
      "x": 6,
      "y": 1
    },
    "image": "Recyclomancy.png",
    "requires": [
      "v_wasteful"
    ],
    "config": {
      "extra": 1
    },
    "text": [
      "每回合",
      "弃牌次数",
      "永久{C:blue}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_tarot_merchant",
    "enName": "Tarot Merchant",
    "zhName": "塔罗牌商人",
    "order": 17,
    "cost": 10,
    "pos": {
      "x": 1,
      "y": 0
    },
    "image": "Tarot Merchant.png",
    "requires": [],
    "config": {
      "extra": 2.4,
      "extra_disp": 2
    },
    "text": [
      "商店内",
      "{C:tarot}塔罗牌{}",
      "出现频率{C:attention}X#1#{}"
    ],
    "vars": [
      2.4
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_tarot_tycoon",
    "enName": "Tarot Tycoon",
    "zhName": "塔罗大亨",
    "order": 18,
    "cost": 10,
    "pos": {
      "x": 1,
      "y": 1
    },
    "image": "Tarot Tycoon.png",
    "requires": [
      "v_tarot_merchant"
    ],
    "config": {
      "extra": 8,
      "extra_disp": 4
    },
    "text": [
      "商店内",
      "{C:tarot}塔罗牌{}",
      "出现频率{C:attention}X#1#{}"
    ],
    "vars": [
      8
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_planet_merchant",
    "enName": "Planet Merchant",
    "zhName": "星球牌商人",
    "order": 19,
    "cost": 10,
    "pos": {
      "x": 2,
      "y": 0
    },
    "image": "Planet Merchant.png",
    "requires": [],
    "config": {
      "extra": 2.4,
      "extra_disp": 2
    },
    "text": [
      "商店内",
      "{C:planet}星球牌{}",
      "出现频率{C:attention}X#1#{}"
    ],
    "vars": [
      2.4
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_planet_tycoon",
    "enName": "Planet Tycoon",
    "zhName": "星球大亨",
    "order": 20,
    "cost": 10,
    "pos": {
      "x": 2,
      "y": 1
    },
    "image": "Planet Tycoon.png",
    "requires": [
      "v_planet_merchant"
    ],
    "config": {
      "extra": 8,
      "extra_disp": 4
    },
    "text": [
      "商店内",
      "{C:tarot}星球牌{}",
      "出现频率{C:attention}X#1#{}"
    ],
    "vars": [
      8
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_seed_money",
    "enName": "Seed Money",
    "zhName": "种子基金",
    "order": 21,
    "cost": 10,
    "pos": {
      "x": 1,
      "y": 2
    },
    "image": "Seed Money.png",
    "requires": [],
    "config": {
      "extra": 50
    },
    "text": [
      "每回合",
      "可获得利息的上限",
      "提高到{C:money}$#1#{}"
    ],
    "vars": [
      50
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_money_tree",
    "enName": "Money Tree",
    "zhName": "摇钱树",
    "order": 22,
    "cost": 10,
    "pos": {
      "x": 1,
      "y": 3
    },
    "image": "Money Tree.png",
    "requires": [
      "v_seed_money"
    ],
    "config": {
      "extra": 100
    },
    "text": [
      "每回合",
      "可获得利息的上限",
      "提高到{C:money}$#1#{}"
    ],
    "vars": [
      100
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_blank",
    "enName": "Blank",
    "zhName": "空白",
    "order": 23,
    "cost": 10,
    "pos": {
      "x": 7,
      "y": 0
    },
    "image": "Blank.png",
    "requires": [],
    "config": {
      "extra": 5
    },
    "text": [
      "{C:inactive}什么都没有？"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_antimatter",
    "enName": "Antimatter",
    "zhName": "反物质",
    "order": 24,
    "cost": 10,
    "pos": {
      "x": 7,
      "y": 1
    },
    "image": "Antimatter.png",
    "requires": [
      "v_blank"
    ],
    "config": {
      "extra": 15
    },
    "text": [
      "小丑牌槽位{C:dark_edition}+1{}"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_magic_trick",
    "enName": "Magic Trick",
    "zhName": "魔术",
    "order": 25,
    "cost": 10,
    "pos": {
      "x": 4,
      "y": 2
    },
    "image": "Magic Trick.png",
    "requires": [],
    "config": {
      "extra": 4
    },
    "text": [
      "{C:attention}商店{}里面",
      "有{C:attention}游戏牌{}",
      "可供选购"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_illusion",
    "enName": "Illusion",
    "zhName": "幻象",
    "order": 26,
    "cost": 10,
    "pos": {
      "x": 4,
      "y": 3
    },
    "image": "Illusion.png",
    "requires": [
      "v_magic_trick"
    ],
    "config": {
      "extra": 4
    },
    "text": [
      "商店内的{C:attention}游戏牌{}",
      "可以是{C:enhanced}增强卡牌{}、",
      "{C:dark_edition}不同版本{}、和/或{C:attention}蜡封{}"
    ],
    "vars": [],
    "colour": "#cb724c"
  },
  {
    "key": "v_directors_cut",
    "enName": "Director's Cut",
    "zhName": "导演剪辑版",
    "order": 29,
    "cost": 10,
    "pos": {
      "x": 6,
      "y": 2
    },
    "image": "Director.png",
    "requires": [],
    "config": {
      "extra": 10
    },
    "text": [
      "可以重掷Boss盲注",
      "每个底注限重掷{C:attention}1{}次",
      "每次花费{C:money}$#1#{}"
    ],
    "vars": [
      10
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_retcon",
    "enName": "Retcon",
    "zhName": "重构",
    "order": 30,
    "cost": 10,
    "pos": {
      "x": 6,
      "y": 3
    },
    "image": "Retcon.png",
    "requires": [
      "v_directors_cut"
    ],
    "config": {
      "extra": 10
    },
    "text": [
      "重掷Boss盲注",
      "{C:attention}不限{}次数",
      "每次重掷花费{C:money}$#1#{}"
    ],
    "vars": [
      10
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_paint_brush",
    "enName": "Paint Brush",
    "zhName": "油漆刷",
    "order": 31,
    "cost": 10,
    "pos": {
      "x": 7,
      "y": 2
    },
    "image": "Paint Brush.png",
    "requires": [],
    "config": {
      "extra": 1
    },
    "text": [
      "手牌上限{C:attention}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#cb724c"
  },
  {
    "key": "v_palette",
    "enName": "Palette",
    "zhName": "调色板",
    "order": 32,
    "cost": 10,
    "pos": {
      "x": 7,
      "y": 3
    },
    "image": "Palette.png",
    "requires": [
      "v_paint_brush"
    ],
    "config": {
      "extra": 1
    },
    "text": [
      "手牌上限{C:attention}+#1#{}"
    ],
    "vars": [
      1
    ],
    "colour": "#cb724c"
  }
];
